-- Part 1: Products (1-500)
-- ========================================
-- 3. INSERT PRODUCTS (1000+ products)
-- ========================================

-- Smartphones (100)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1, 'Apple Max 128GB', 'Electronics', 'Smartphones', 'Apple Max 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (2, 'Samsung Note ', 'Electronics', 'Smartphones', 'Samsung Note  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (3, 'Nothing Max ', 'Electronics', 'Smartphones', 'Nothing Max  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (4, 'Motorola Pro 128GB', 'Electronics', 'Smartphones', 'Motorola Pro 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (5, 'Realme 11T ', 'Electronics', 'Smartphones', 'Realme 11T  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (6, 'Samsung A54 128GB', 'Electronics', 'Smartphones', 'Samsung A54 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (7, 'Motorola Max 256GB', 'Electronics', 'Smartphones', 'Motorola Max 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (8, 'Oppo 11T 5G', 'Electronics', 'Smartphones', 'Oppo 11T 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (9, 'Xiaomi Plus 128GB', 'Electronics', 'Smartphones', 'Xiaomi Plus 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (10, 'Apple Note ', 'Electronics', 'Smartphones', 'Apple Note  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (11, 'Vivo Max 128GB', 'Electronics', 'Smartphones', 'Vivo Max 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (12, 'Google S24 5G', 'Electronics', 'Smartphones', 'Google S24 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (13, 'Motorola 13 256GB', 'Electronics', 'Smartphones', 'Motorola 13 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (14, 'Motorola Plus ', 'Electronics', 'Smartphones', 'Motorola Plus  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (15, 'Oppo 15 128GB', 'Electronics', 'Smartphones', 'Oppo 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (16, 'Oppo Ultra 5G', 'Electronics', 'Smartphones', 'Oppo Ultra 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (17, 'Google Note 128GB', 'Electronics', 'Smartphones', 'Google Note 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (18, 'Apple S24 5G', 'Electronics', 'Smartphones', 'Apple S24 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (19, 'Vivo 14 ', 'Electronics', 'Smartphones', 'Vivo 14  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (20, 'Nothing 12 Pro ', 'Electronics', 'Smartphones', 'Nothing 12 Pro  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (21, 'Google S23 128GB', 'Electronics', 'Smartphones', 'Google S23 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (22, 'Apple S24 ', 'Electronics', 'Smartphones', 'Apple S24  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (23, 'Vivo 13 128GB', 'Electronics', 'Smartphones', 'Vivo 13 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (24, 'Google M14 256GB', 'Electronics', 'Smartphones', 'Google M14 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (25, 'OnePlus Plus 5G', 'Electronics', 'Smartphones', 'OnePlus Plus 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (26, 'Oppo Note 256GB', 'Electronics', 'Smartphones', 'Oppo Note 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (27, 'Samsung S23 256GB', 'Electronics', 'Smartphones', 'Samsung S23 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (28, 'Realme S23 128GB', 'Electronics', 'Smartphones', 'Realme S23 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (29, 'Samsung S24 5G', 'Electronics', 'Smartphones', 'Samsung S24 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (30, 'Apple 11T 256GB', 'Electronics', 'Smartphones', 'Apple 11T 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (31, 'Oppo Note ', 'Electronics', 'Smartphones', 'Oppo Note  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (32, 'OnePlus 15 128GB', 'Electronics', 'Smartphones', 'OnePlus 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (33, 'Nothing M14 ', 'Electronics', 'Smartphones', 'Nothing M14  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (34, 'Nothing 12 Pro 128GB', 'Electronics', 'Smartphones', 'Nothing 12 Pro 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (35, 'Google S23 5G', 'Electronics', 'Smartphones', 'Google S23 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (36, 'Google M14 5G', 'Electronics', 'Smartphones', 'Google M14 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (37, 'Motorola Pro ', 'Electronics', 'Smartphones', 'Motorola Pro  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (38, 'OnePlus Pro 5G', 'Electronics', 'Smartphones', 'OnePlus Pro 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (39, 'OnePlus S23 256GB', 'Electronics', 'Smartphones', 'OnePlus S23 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (40, 'Xiaomi S23 ', 'Electronics', 'Smartphones', 'Xiaomi S23  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (41, 'Motorola 15 128GB', 'Electronics', 'Smartphones', 'Motorola 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (42, 'Realme 13 ', 'Electronics', 'Smartphones', 'Realme 13  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (43, 'Vivo 15 5G', 'Electronics', 'Smartphones', 'Vivo 15 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (44, 'Motorola 12 Pro 256GB', 'Electronics', 'Smartphones', 'Motorola 12 Pro 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (45, 'Nothing 14 256GB', 'Electronics', 'Smartphones', 'Nothing 14 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (46, 'Oppo Ultra 128GB', 'Electronics', 'Smartphones', 'Oppo Ultra 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (47, 'Oppo Pro 128GB', 'Electronics', 'Smartphones', 'Oppo Pro 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (48, 'Apple A54 5G', 'Electronics', 'Smartphones', 'Apple A54 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (49, 'Google 15 128GB', 'Electronics', 'Smartphones', 'Google 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (50, 'Xiaomi 15 256GB', 'Electronics', 'Smartphones', 'Xiaomi 15 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (51, 'Nothing 12 Pro 5G', 'Electronics', 'Smartphones', 'Nothing 12 Pro 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (52, 'Vivo Ultra 256GB', 'Electronics', 'Smartphones', 'Vivo Ultra 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (53, 'Realme S24 128GB', 'Electronics', 'Smartphones', 'Realme S24 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (54, 'Motorola Note 5G', 'Electronics', 'Smartphones', 'Motorola Note 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (55, 'Motorola 11T 256GB', 'Electronics', 'Smartphones', 'Motorola 11T 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (56, 'Google 12 Pro 5G', 'Electronics', 'Smartphones', 'Google 12 Pro 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (57, 'Oppo 13 128GB', 'Electronics', 'Smartphones', 'Oppo 13 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (58, 'Motorola A54 5G', 'Electronics', 'Smartphones', 'Motorola A54 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (59, 'Apple 15 ', 'Electronics', 'Smartphones', 'Apple 15  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (60, 'Oppo 12 Pro 5G', 'Electronics', 'Smartphones', 'Oppo 12 Pro 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (61, 'Google S24 256GB', 'Electronics', 'Smartphones', 'Google S24 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (62, 'Oppo Plus ', 'Electronics', 'Smartphones', 'Oppo Plus  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (63, 'Motorola Max ', 'Electronics', 'Smartphones', 'Motorola Max  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (64, 'Google Plus 256GB', 'Electronics', 'Smartphones', 'Google Plus 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (65, 'OnePlus Plus 5G', 'Electronics', 'Smartphones', 'OnePlus Plus 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (66, 'Xiaomi 14 5G', 'Electronics', 'Smartphones', 'Xiaomi 14 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (67, 'Nothing Pro 256GB', 'Electronics', 'Smartphones', 'Nothing Pro 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (68, 'Google M14 128GB', 'Electronics', 'Smartphones', 'Google M14 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (69, 'Vivo 13 256GB', 'Electronics', 'Smartphones', 'Vivo 13 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (70, 'Apple A54 128GB', 'Electronics', 'Smartphones', 'Apple A54 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (71, 'Oppo 15 128GB', 'Electronics', 'Smartphones', 'Oppo 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (72, 'Vivo Note 128GB', 'Electronics', 'Smartphones', 'Vivo Note 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (73, 'OnePlus 14 256GB', 'Electronics', 'Smartphones', 'OnePlus 14 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (74, 'Apple S23 5G', 'Electronics', 'Smartphones', 'Apple S23 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (75, 'Nothing M14 5G', 'Electronics', 'Smartphones', 'Nothing M14 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (76, 'Xiaomi 15 128GB', 'Electronics', 'Smartphones', 'Xiaomi 15 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (77, 'Samsung Note 128GB', 'Electronics', 'Smartphones', 'Samsung Note 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (78, 'Apple Max 5G', 'Electronics', 'Smartphones', 'Apple Max 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (79, 'Realme 11T 5G', 'Electronics', 'Smartphones', 'Realme 11T 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (80, 'Apple 11T 128GB', 'Electronics', 'Smartphones', 'Apple 11T 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (81, 'Realme 14 256GB', 'Electronics', 'Smartphones', 'Realme 14 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (82, 'Samsung 15 5G', 'Electronics', 'Smartphones', 'Samsung 15 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (83, 'Samsung S24 5G', 'Electronics', 'Smartphones', 'Samsung S24 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (84, 'OnePlus 12 Pro 256GB', 'Electronics', 'Smartphones', 'OnePlus 12 Pro 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (85, 'OnePlus Max 256GB', 'Electronics', 'Smartphones', 'OnePlus Max 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (86, 'Samsung 11T 5G', 'Electronics', 'Smartphones', 'Samsung 11T 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (87, 'OnePlus M14 ', 'Electronics', 'Smartphones', 'OnePlus M14  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (88, 'Xiaomi Ultra 128GB', 'Electronics', 'Smartphones', 'Xiaomi Ultra 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (89, 'Motorola Max 128GB', 'Electronics', 'Smartphones', 'Motorola Max 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (90, 'Realme Max 256GB', 'Electronics', 'Smartphones', 'Realme Max 256GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (91, 'Oppo 12 Pro 5G', 'Electronics', 'Smartphones', 'Oppo 12 Pro 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (92, 'Motorola A54 ', 'Electronics', 'Smartphones', 'Motorola A54  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (93, 'Realme Max 5G', 'Electronics', 'Smartphones', 'Realme Max 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (94, 'OnePlus Max ', 'Electronics', 'Smartphones', 'OnePlus Max  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (95, 'OnePlus Pro 128GB', 'Electronics', 'Smartphones', 'OnePlus Pro 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (96, 'Realme Max ', 'Electronics', 'Smartphones', 'Realme Max  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (97, 'Samsung S23 5G', 'Electronics', 'Smartphones', 'Samsung S23 5G smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (98, 'Realme 12 Pro 128GB', 'Electronics', 'Smartphones', 'Realme 12 Pro 128GB smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (99, 'Google 11T ', 'Electronics', 'Smartphones', 'Google 11T  smartphone with latest features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (100, 'Motorola Pro 256GB', 'Electronics', 'Smartphones', 'Motorola Pro 256GB smartphone with latest features');

-- Featured Products
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (101, 'iPhone 15 Pro', 'Electronics', 'Smartphones', 'Latest iPhone with A17 Pro chip');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (102, 'MacBook Air M3', 'Electronics', 'Laptops', '15-inch MacBook Air with M3 chip');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (103, 'Samsung Galaxy S24 Ultra', 'Electronics', 'Smartphones', 'Flagship Samsung with AI features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (104, 'Samsung 55" QLED TV', 'Electronics', 'Televisions', '4K QLED Smart TV');

-- Laptops (80)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (105, 'Lenovo ThinkPad i5', 'Electronics', 'Laptops', 'Lenovo ThinkPad i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (106, 'Apple TUF Ryzen 5', 'Electronics', 'Laptops', 'Apple TUF Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (107, 'Acer ThinkPad Ryzen 7', 'Electronics', 'Laptops', 'Acer ThinkPad Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (108, 'Acer Pavilion i5', 'Electronics', 'Laptops', 'Acer Pavilion i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (109, 'MSI ThinkPad Ryzen 7', 'Electronics', 'Laptops', 'MSI ThinkPad Ryzen 7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (110, 'Apple IdeaPad Ryzen 7', 'Electronics', 'Laptops', 'Apple IdeaPad Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (111, 'Dell Envy Ryzen 5', 'Electronics', 'Laptops', 'Dell Envy Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (112, 'Acer Envy Ryzen 5', 'Electronics', 'Laptops', 'Acer Envy Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (113, 'Lenovo Pavilion Ryzen 5', 'Electronics', 'Laptops', 'Lenovo Pavilion Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (114, 'Asus ROG i7', 'Electronics', 'Laptops', 'Asus ROG i7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (115, 'HP Pavilion i7', 'Electronics', 'Laptops', 'HP Pavilion i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (116, 'Razer IdeaPad Ryzen 5', 'Electronics', 'Laptops', 'Razer IdeaPad Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (117, 'Apple Inspiron Ryzen 5', 'Electronics', 'Laptops', 'Apple Inspiron Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (118, 'HP ROG i7', 'Electronics', 'Laptops', 'HP ROG i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (119, 'Asus ROG Ryzen 7', 'Electronics', 'Laptops', 'Asus ROG Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (120, 'Acer ROG i5', 'Electronics', 'Laptops', 'Acer ROG i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (121, 'Dell Pavilion Ryzen 5', 'Electronics', 'Laptops', 'Dell Pavilion Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (122, 'Razer Envy i5', 'Electronics', 'Laptops', 'Razer Envy i5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (123, 'MSI XPS i7', 'Electronics', 'Laptops', 'MSI XPS i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (124, 'Razer ROG Ryzen 7', 'Electronics', 'Laptops', 'Razer ROG Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (125, 'Asus TUF Ryzen 5', 'Electronics', 'Laptops', 'Asus TUF Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (126, 'Apple Pavilion i5', 'Electronics', 'Laptops', 'Apple Pavilion i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (127, 'Apple VivoBook i5', 'Electronics', 'Laptops', 'Apple VivoBook i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (128, 'Apple ROG i5', 'Electronics', 'Laptops', 'Apple ROG i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (129, 'Asus XPS i5', 'Electronics', 'Laptops', 'Asus XPS i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (130, 'Apple Pavilion i7', 'Electronics', 'Laptops', 'Apple Pavilion i7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (131, 'Lenovo XPS Ryzen 5', 'Electronics', 'Laptops', 'Lenovo XPS Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (132, 'Asus ROG i5', 'Electronics', 'Laptops', 'Asus ROG i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (133, 'MSI IdeaPad Ryzen 7', 'Electronics', 'Laptops', 'MSI IdeaPad Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (134, 'Acer XPS Ryzen 5', 'Electronics', 'Laptops', 'Acer XPS Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (135, 'Dell Inspiron Ryzen 7', 'Electronics', 'Laptops', 'Dell Inspiron Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (136, 'Asus Pavilion Ryzen 7', 'Electronics', 'Laptops', 'Asus Pavilion Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (137, 'HP ROG Ryzen 7', 'Electronics', 'Laptops', 'HP ROG Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (138, 'MSI VivoBook Ryzen 5', 'Electronics', 'Laptops', 'MSI VivoBook Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (139, 'HP Inspiron Ryzen 5', 'Electronics', 'Laptops', 'HP Inspiron Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (140, 'Razer ThinkPad Ryzen 5', 'Electronics', 'Laptops', 'Razer ThinkPad Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (141, 'Asus IdeaPad i7', 'Electronics', 'Laptops', 'Asus IdeaPad i7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (142, 'HP TUF i5', 'Electronics', 'Laptops', 'HP TUF i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (143, 'Dell ROG i5', 'Electronics', 'Laptops', 'Dell ROG i5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (144, 'Asus IdeaPad Ryzen 5', 'Electronics', 'Laptops', 'Asus IdeaPad Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (145, 'Apple ThinkPad Ryzen 5', 'Electronics', 'Laptops', 'Apple ThinkPad Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (146, 'Razer IdeaPad i7', 'Electronics', 'Laptops', 'Razer IdeaPad i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (147, 'HP Inspiron Ryzen 5', 'Electronics', 'Laptops', 'HP Inspiron Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (148, 'MSI Inspiron Ryzen 7', 'Electronics', 'Laptops', 'MSI Inspiron Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (149, 'MSI XPS i5', 'Electronics', 'Laptops', 'MSI XPS i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (150, 'Acer TUF Ryzen 5', 'Electronics', 'Laptops', 'Acer TUF Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (151, 'Lenovo XPS Ryzen 5', 'Electronics', 'Laptops', 'Lenovo XPS Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (152, 'HP ROG Ryzen 7', 'Electronics', 'Laptops', 'HP ROG Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (153, 'Asus IdeaPad Ryzen 7', 'Electronics', 'Laptops', 'Asus IdeaPad Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (154, 'Acer IdeaPad i7', 'Electronics', 'Laptops', 'Acer IdeaPad i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (155, 'Asus VivoBook i5', 'Electronics', 'Laptops', 'Asus VivoBook i5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (156, 'Dell ThinkPad i5', 'Electronics', 'Laptops', 'Dell ThinkPad i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (157, 'Asus VivoBook Ryzen 7', 'Electronics', 'Laptops', 'Asus VivoBook Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (158, 'MSI VivoBook Ryzen 7', 'Electronics', 'Laptops', 'MSI VivoBook Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (159, 'Razer Envy i5', 'Electronics', 'Laptops', 'Razer Envy i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (160, 'MSI Pavilion i5', 'Electronics', 'Laptops', 'MSI Pavilion i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (161, 'Apple Inspiron Ryzen 5', 'Electronics', 'Laptops', 'Apple Inspiron Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (162, 'MSI VivoBook Ryzen 7', 'Electronics', 'Laptops', 'MSI VivoBook Ryzen 7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (163, 'Razer Envy i7', 'Electronics', 'Laptops', 'Razer Envy i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (164, 'Dell Pavilion i5', 'Electronics', 'Laptops', 'Dell Pavilion i5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (165, 'Apple ThinkPad i7', 'Electronics', 'Laptops', 'Apple ThinkPad i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (166, 'HP XPS Ryzen 7', 'Electronics', 'Laptops', 'HP XPS Ryzen 7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (167, 'Asus Envy Ryzen 7', 'Electronics', 'Laptops', 'Asus Envy Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (168, 'MSI IdeaPad i7', 'Electronics', 'Laptops', 'MSI IdeaPad i7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (169, 'HP IdeaPad i7', 'Electronics', 'Laptops', 'HP IdeaPad i7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (170, 'Razer Inspiron Ryzen 5', 'Electronics', 'Laptops', 'Razer Inspiron Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (171, 'Lenovo XPS i7', 'Electronics', 'Laptops', 'Lenovo XPS i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (172, 'Dell Inspiron Ryzen 5', 'Electronics', 'Laptops', 'Dell Inspiron Ryzen 5 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (173, 'Dell VivoBook i7', 'Electronics', 'Laptops', 'Dell VivoBook i7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (174, 'Razer TUF Ryzen 7', 'Electronics', 'Laptops', 'Razer TUF Ryzen 7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (175, 'Lenovo TUF i7', 'Electronics', 'Laptops', 'Lenovo TUF i7 laptop with 8GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (176, 'Razer IdeaPad Ryzen 5', 'Electronics', 'Laptops', 'Razer IdeaPad Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (177, 'Razer Inspiron Ryzen 5', 'Electronics', 'Laptops', 'Razer Inspiron Ryzen 5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (178, 'Apple Pavilion i5', 'Electronics', 'Laptops', 'Apple Pavilion i5 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (179, 'MSI Envy i7', 'Electronics', 'Laptops', 'MSI Envy i7 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (180, 'MSI XPS i5', 'Electronics', 'Laptops', 'MSI XPS i5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (181, 'Asus XPS i7', 'Electronics', 'Laptops', 'Asus XPS i7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (182, 'Dell TUF Ryzen 5', 'Electronics', 'Laptops', 'Dell TUF Ryzen 5 laptop with 32GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (183, 'Acer XPS i7', 'Electronics', 'Laptops', 'Acer XPS i7 laptop with 16GB RAM');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (184, 'Razer ROG Ryzen 7', 'Electronics', 'Laptops', 'Razer ROG Ryzen 7 laptop with 8GB RAM');

-- Televisions (60)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (185, 'Mi 32" UHD Smart TV', 'Electronics', 'Televisions', '32" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (186, 'OnePlus 32" QLED Smart TV', 'Electronics', 'Televisions', '32" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (187, 'Mi 65" OLED Smart TV', 'Electronics', 'Televisions', '65" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (188, 'LG 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (189, 'TCL 75" QLED Smart TV', 'Electronics', 'Televisions', '75" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (190, 'LG 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (191, 'Sony 43" UHD Smart TV', 'Electronics', 'Televisions', '43" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (192, 'OnePlus 75" UHD Smart TV', 'Electronics', 'Televisions', '75" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (193, 'Sony 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (194, 'Sony 43" QLED Smart TV', 'Electronics', 'Televisions', '43" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (195, 'VU 32" LED Smart TV', 'Electronics', 'Televisions', '32" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (196, 'TCL 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (197, 'TCL 55" OLED Smart TV', 'Electronics', 'Televisions', '55" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (198, 'Mi 43" QLED Smart TV', 'Electronics', 'Televisions', '43" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (199, 'VU 65" LED Smart TV', 'Electronics', 'Televisions', '65" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (200, 'Mi 65" OLED Smart TV', 'Electronics', 'Televisions', '65" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (201, 'VU 55" OLED Smart TV', 'Electronics', 'Televisions', '55" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (202, 'TCL 43" LED Smart TV', 'Electronics', 'Televisions', '43" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (203, 'VU 55" OLED Smart TV', 'Electronics', 'Televisions', '55" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (204, 'OnePlus 32" QLED Smart TV', 'Electronics', 'Televisions', '32" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (205, 'Samsung 43" QLED Smart TV', 'Electronics', 'Televisions', '43" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (206, 'Mi 50" OLED Smart TV', 'Electronics', 'Televisions', '50" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (207, 'Mi 65" OLED Smart TV', 'Electronics', 'Televisions', '65" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (208, 'LG 75" LED Smart TV', 'Electronics', 'Televisions', '75" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (209, 'LG 55" OLED Smart TV', 'Electronics', 'Televisions', '55" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (210, 'LG 32" UHD Smart TV', 'Electronics', 'Televisions', '32" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (211, 'VU 32" UHD Smart TV', 'Electronics', 'Televisions', '32" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (212, 'Mi 75" QLED Smart TV', 'Electronics', 'Televisions', '75" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (213, 'Mi 32" LED Smart TV', 'Electronics', 'Televisions', '32" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (214, 'VU 32" QLED Smart TV', 'Electronics', 'Televisions', '32" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (215, 'LG 55" QLED Smart TV', 'Electronics', 'Televisions', '55" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (216, 'Sony 32" QLED Smart TV', 'Electronics', 'Televisions', '32" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (217, 'LG 43" OLED Smart TV', 'Electronics', 'Televisions', '43" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (218, 'Sony 32" OLED Smart TV', 'Electronics', 'Televisions', '32" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (219, 'Mi 65" OLED Smart TV', 'Electronics', 'Televisions', '65" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (220, 'TCL 32" UHD Smart TV', 'Electronics', 'Televisions', '32" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (221, 'Sony 32" OLED Smart TV', 'Electronics', 'Televisions', '32" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (222, 'TCL 43" UHD Smart TV', 'Electronics', 'Televisions', '43" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (223, 'Samsung 32" OLED Smart TV', 'Electronics', 'Televisions', '32" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (224, 'VU 75" QLED Smart TV', 'Electronics', 'Televisions', '75" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (225, 'Samsung 75" UHD Smart TV', 'Electronics', 'Televisions', '75" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (226, 'VU 43" UHD Smart TV', 'Electronics', 'Televisions', '43" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (227, 'Sony 32" OLED Smart TV', 'Electronics', 'Televisions', '32" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (228, 'Samsung 32" QLED Smart TV', 'Electronics', 'Televisions', '32" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (229, 'VU 50" UHD Smart TV', 'Electronics', 'Televisions', '50" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (230, 'LG 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (231, 'LG 65" UHD Smart TV', 'Electronics', 'Televisions', '65" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (232, 'TCL 55" LED Smart TV', 'Electronics', 'Televisions', '55" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (233, 'LG 65" QLED Smart TV', 'Electronics', 'Televisions', '65" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (234, 'Sony 55" UHD Smart TV', 'Electronics', 'Televisions', '55" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (235, 'LG 43" LED Smart TV', 'Electronics', 'Televisions', '43" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (236, 'OnePlus 55" OLED Smart TV', 'Electronics', 'Televisions', '55" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (237, 'VU 43" QLED Smart TV', 'Electronics', 'Televisions', '43" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (238, 'VU 65" UHD Smart TV', 'Electronics', 'Televisions', '65" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (239, 'Samsung 50" OLED Smart TV', 'Electronics', 'Televisions', '50" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (240, 'Mi 75" OLED Smart TV', 'Electronics', 'Televisions', '75" OLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (241, 'Mi 43" UHD Smart TV', 'Electronics', 'Televisions', '43" UHD television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (242, 'Sony 43" QLED Smart TV', 'Electronics', 'Televisions', '43" QLED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (243, 'Sony 65" LED Smart TV', 'Electronics', 'Televisions', '65" LED television with smart features');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (244, 'Samsung 65" QLED Smart TV', 'Electronics', 'Televisions', '65" QLED television with smart features');

-- Headphones & Audio (60)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (245, 'Boat Over-Ear Headphones ', 'Electronics', 'Audio', 'Boat Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (246, 'Boat Bluetooth Speaker Ultra', 'Electronics', 'Audio', 'Boat Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (247, 'Audio-Technica Soundbar Ultra', 'Electronics', 'Audio', 'Audio-Technica Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (248, 'Sony Over-Ear Headphones Pro', 'Electronics', 'Audio', 'Sony Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (249, 'Boat Wireless Earbuds ', 'Electronics', 'Audio', 'Boat Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (250, 'Sennheiser Bluetooth Speaker Plus', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (251, 'Sennheiser Over-Ear Headphones Max', 'Electronics', 'Audio', 'Sennheiser Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (252, 'JBL Wireless Earbuds Plus', 'Electronics', 'Audio', 'JBL Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (253, 'Beats Wireless Earbuds Max', 'Electronics', 'Audio', 'Beats Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (254, 'Boat Wireless Earbuds Max', 'Electronics', 'Audio', 'Boat Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (255, 'Beats Wireless Earbuds Max', 'Electronics', 'Audio', 'Beats Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (256, 'Sennheiser Bluetooth Speaker Plus', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (257, 'Audio-Technica Soundbar Ultra', 'Electronics', 'Audio', 'Audio-Technica Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (258, 'Sennheiser Over-Ear Headphones Max', 'Electronics', 'Audio', 'Sennheiser Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (259, 'Audio-Technica Soundbar ', 'Electronics', 'Audio', 'Audio-Technica Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (260, 'Sennheiser Wireless Earbuds Plus', 'Electronics', 'Audio', 'Sennheiser Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (261, 'Sony Soundbar Ultra', 'Electronics', 'Audio', 'Sony Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (262, 'Bose Over-Ear Headphones ', 'Electronics', 'Audio', 'Bose Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (263, 'Sony Bluetooth Speaker Ultra', 'Electronics', 'Audio', 'Sony Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (264, 'Beats Soundbar ', 'Electronics', 'Audio', 'Beats Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (265, 'Sony Wireless Earbuds Ultra', 'Electronics', 'Audio', 'Sony Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (266, 'Boat Over-Ear Headphones ', 'Electronics', 'Audio', 'Boat Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (267, 'JBL Over-Ear Headphones Ultra', 'Electronics', 'Audio', 'JBL Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (268, 'Boat Wireless Earbuds Ultra', 'Electronics', 'Audio', 'Boat Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (269, 'Sennheiser Over-Ear Headphones Plus', 'Electronics', 'Audio', 'Sennheiser Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (270, 'Sony Bluetooth Speaker Ultra', 'Electronics', 'Audio', 'Sony Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (271, 'Beats Over-Ear Headphones Pro', 'Electronics', 'Audio', 'Beats Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (272, 'Sennheiser Soundbar ', 'Electronics', 'Audio', 'Sennheiser Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (273, 'Sony Wireless Earbuds ', 'Electronics', 'Audio', 'Sony Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (274, 'JBL Wireless Earbuds Pro', 'Electronics', 'Audio', 'JBL Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (275, 'Sennheiser Bluetooth Speaker Ultra', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (276, 'JBL Bluetooth Speaker Max', 'Electronics', 'Audio', 'JBL Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (277, 'Audio-Technica Soundbar Max', 'Electronics', 'Audio', 'Audio-Technica Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (278, 'Audio-Technica Bluetooth Speaker ', 'Electronics', 'Audio', 'Audio-Technica Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (279, 'Sennheiser Over-Ear Headphones Max', 'Electronics', 'Audio', 'Sennheiser Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (280, 'Sennheiser Soundbar Ultra', 'Electronics', 'Audio', 'Sennheiser Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (281, 'Beats Soundbar Max', 'Electronics', 'Audio', 'Beats Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (282, 'Beats Over-Ear Headphones ', 'Electronics', 'Audio', 'Beats Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (283, 'Sennheiser Bluetooth Speaker ', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (284, 'JBL Bluetooth Speaker Plus', 'Electronics', 'Audio', 'JBL Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (285, 'JBL Soundbar Pro', 'Electronics', 'Audio', 'JBL Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (286, 'Sony Soundbar Pro', 'Electronics', 'Audio', 'Sony Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (287, 'Audio-Technica Bluetooth Speaker Ultra', 'Electronics', 'Audio', 'Audio-Technica Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (288, 'Beats Wireless Earbuds ', 'Electronics', 'Audio', 'Beats Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (289, 'JBL Over-Ear Headphones Pro', 'Electronics', 'Audio', 'JBL Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (290, 'Boat Soundbar ', 'Electronics', 'Audio', 'Boat Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (291, 'Sennheiser Soundbar Pro', 'Electronics', 'Audio', 'Sennheiser Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (292, 'JBL Soundbar Plus', 'Electronics', 'Audio', 'JBL Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (293, 'Beats Over-Ear Headphones Pro', 'Electronics', 'Audio', 'Beats Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (294, 'JBL Over-Ear Headphones ', 'Electronics', 'Audio', 'JBL Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (295, 'Sony Wireless Earbuds Ultra', 'Electronics', 'Audio', 'Sony Wireless Earbuds with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (296, 'Sony Soundbar ', 'Electronics', 'Audio', 'Sony Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (297, 'Bose Soundbar Ultra', 'Electronics', 'Audio', 'Bose Soundbar with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (298, 'Sennheiser Bluetooth Speaker Max', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (299, 'Beats Bluetooth Speaker ', 'Electronics', 'Audio', 'Beats Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (300, 'Boat Over-Ear Headphones Pro', 'Electronics', 'Audio', 'Boat Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (301, 'Sennheiser Bluetooth Speaker ', 'Electronics', 'Audio', 'Sennheiser Bluetooth Speaker with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (302, 'Audio-Technica Over-Ear Headphones Pro', 'Electronics', 'Audio', 'Audio-Technica Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (303, 'Bose Over-Ear Headphones Ultra', 'Electronics', 'Audio', 'Bose Over-Ear Headphones with premium sound');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (304, 'JBL Bluetooth Speaker Pro', 'Electronics', 'Audio', 'JBL Bluetooth Speaker with premium sound');

-- Flight Tickets (200)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (305, 'Flight Mumbai → Bangalore on 2025-12-23', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (306, 'Flight Delhi → Srinagar on 2025-11-20', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (307, 'Flight Ahmedabad → Bangalore on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (308, 'Flight Delhi → Singapore on 2026-02-07', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (309, 'Flight Ahmedabad → Bangalore on 2026-01-27', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (310, 'Flight Kochi → Delhi on 2026-01-13', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (311, 'Flight Mumbai → New York on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (312, 'Flight Delhi → Goa on 2026-01-15', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (313, 'Flight Bangalore → Hyderabad on 2025-12-23', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (314, 'Flight Delhi → Singapore on 2025-12-18', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (315, 'Flight Bangalore → London on 2026-01-10', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (316, 'Flight Mumbai → Dubai on 2026-02-03', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (317, 'Flight Mumbai → Bangalore on 2025-11-26', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (318, 'Flight Jaipur → Mumbai on 2025-12-05', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (319, 'Flight Mumbai → Bangalore on 2025-12-09', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (320, 'Flight Bangalore → London on 2026-02-14', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (321, 'Flight Chennai → Kolkata on 2025-12-25', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (322, 'Flight Mumbai → New York on 2026-01-10', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (323, 'Flight Mumbai → Dubai on 2026-01-07', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (324, 'Flight Delhi → Srinagar on 2026-01-06', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (325, 'Flight Mumbai → Dubai on 2026-01-25', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (326, 'Flight Jaipur → Mumbai on 2026-02-13', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (327, 'Flight Mumbai → New York on 2025-12-05', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (328, 'Flight Bangalore → Hyderabad on 2025-12-14', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (329, 'Flight Mumbai → Bangalore on 2026-01-17', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (330, 'Flight Bangalore → London on 2026-01-24', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (331, 'Flight Jaipur → Mumbai on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (332, 'Flight Jaipur → Mumbai on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (333, 'Flight Bangalore → Hyderabad on 2025-12-02', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (334, 'Flight Pune → Delhi on 2025-12-06', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (335, 'Flight Bangalore → London on 2025-11-21', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (336, 'Flight Jaipur → Mumbai on 2025-11-17', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (337, 'Flight Ahmedabad → Bangalore on 2026-01-04', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (338, 'Flight Mumbai → Dubai on 2025-12-16', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (339, 'Flight Bangalore → London on 2025-11-18', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (340, 'Flight Ahmedabad → Bangalore on 2026-01-10', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (341, 'Flight Ahmedabad → Bangalore on 2025-12-03', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (342, 'Flight Delhi → Goa on 2025-12-28', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (343, 'Flight Delhi → Mumbai on 2026-01-12', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (344, 'Flight Delhi → Mumbai on 2025-11-29', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (345, 'Flight Mumbai → Bangalore on 2026-01-27', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (346, 'Flight Delhi → Singapore on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (347, 'Flight Kochi → Delhi on 2025-12-14', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (348, 'Flight Delhi → Singapore on 2025-12-11', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (349, 'Flight Delhi → Srinagar on 2026-02-06', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (350, 'Flight Delhi → Srinagar on 2026-02-12', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (351, 'Flight Bangalore → Hyderabad on 2025-11-21', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (352, 'Flight Delhi → Goa on 2026-01-07', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (353, 'Flight Mumbai → Dubai on 2025-12-29', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (354, 'Flight Delhi → Srinagar on 2026-02-04', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (355, 'Flight Chennai → Kolkata on 2026-02-05', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (356, 'Flight Mumbai → New York on 2026-01-09', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (357, 'Flight Jaipur → Mumbai on 2026-01-16', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (358, 'Flight Kochi → Delhi on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (359, 'Flight Bangalore → London on 2026-02-01', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (360, 'Flight Delhi → Goa on 2025-12-17', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (361, 'Flight Delhi → Singapore on 2025-12-04', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (362, 'Flight Delhi → Singapore on 2025-12-23', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (363, 'Flight Ahmedabad → Bangalore on 2026-01-26', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (364, 'Flight Chennai → Kolkata on 2026-01-13', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (365, 'Flight Delhi → Goa on 2026-01-10', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (366, 'Flight Delhi → Mumbai on 2025-12-01', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (367, 'Flight Jaipur → Mumbai on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (368, 'Flight Ahmedabad → Bangalore on 2025-12-06', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (369, 'Flight Jaipur → Mumbai on 2025-11-24', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (370, 'Flight Delhi → Singapore on 2026-02-09', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (371, 'Flight Delhi → Goa on 2025-11-17', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (372, 'Flight Delhi → Srinagar on 2025-12-03', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (373, 'Flight Delhi → Goa on 2025-12-17', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (374, 'Flight Delhi → Mumbai on 2026-01-22', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (375, 'Flight Delhi → Mumbai on 2025-11-19', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (376, 'Flight Chennai → Kolkata on 2026-02-02', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (377, 'Flight Jaipur → Mumbai on 2025-12-07', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (378, 'Flight Bangalore → Hyderabad on 2026-01-17', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (379, 'Flight Mumbai → Bangalore on 2026-01-16', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (380, 'Flight Bangalore → London on 2026-02-01', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (381, 'Flight Delhi → Srinagar on 2025-11-29', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (382, 'Flight Delhi → Srinagar on 2026-01-02', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (383, 'Flight Delhi → Goa on 2025-11-22', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (384, 'Flight Kochi → Delhi on 2026-02-10', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (385, 'Flight Jaipur → Mumbai on 2026-02-07', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (386, 'Flight Delhi → Singapore on 2025-12-25', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (387, 'Flight Delhi → Singapore on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (388, 'Flight Delhi → Mumbai on 2026-01-29', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (389, 'Flight Mumbai → New York on 2026-01-06', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (390, 'Flight Delhi → Singapore on 2025-12-18', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (391, 'Flight Mumbai → Dubai on 2025-12-22', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (392, 'Flight Pune → Delhi on 2025-12-10', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (393, 'Flight Delhi → Srinagar on 2025-12-01', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (394, 'Flight Bangalore → London on 2025-12-24', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (395, 'Flight Pune → Delhi on 2026-01-04', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (396, 'Flight Delhi → Singapore on 2026-01-16', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (397, 'Flight Kochi → Delhi on 2026-01-03', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (398, 'Flight Ahmedabad → Bangalore on 2026-02-10', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (399, 'Flight Ahmedabad → Bangalore on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (400, 'Flight Delhi → Srinagar on 2026-01-09', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (401, 'Flight Delhi → Mumbai on 2025-12-22', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (402, 'Flight Mumbai → Bangalore on 2025-12-30', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (403, 'Flight Chennai → Kolkata on 2025-12-03', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (404, 'Flight Mumbai → New York on 2026-02-14', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (405, 'Flight Delhi → Goa on 2026-02-11', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (406, 'Flight Ahmedabad → Bangalore on 2025-12-20', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (407, 'Flight Delhi → Srinagar on 2026-02-07', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (408, 'Flight Mumbai → Dubai on 2026-01-24', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (409, 'Flight Pune → Delhi on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (410, 'Flight Jaipur → Mumbai on 2025-11-28', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (411, 'Flight Delhi → Srinagar on 2026-01-06', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (412, 'Flight Bangalore → London on 2026-01-07', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (413, 'Flight Bangalore → London on 2025-12-29', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (414, 'Flight Bangalore → Hyderabad on 2025-12-24', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (415, 'Flight Kochi → Delhi on 2025-11-23', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (416, 'Flight Chennai → Kolkata on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (417, 'Flight Bangalore → London on 2026-01-19', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (418, 'Flight Delhi → Mumbai on 2025-11-20', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (419, 'Flight Chennai → Kolkata on 2025-11-25', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (420, 'Flight Bangalore → London on 2026-02-06', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (421, 'Flight Lucknow → Mumbai on 2026-01-11', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (422, 'Flight Mumbai → Bangalore on 2026-01-25', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (423, 'Flight Mumbai → Dubai on 2025-12-18', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (424, 'Flight Chennai → Kolkata on 2026-02-04', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (425, 'Flight Pune → Delhi on 2026-01-19', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (426, 'Flight Mumbai → Dubai on 2025-12-03', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (427, 'Flight Ahmedabad → Bangalore on 2026-01-19', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (428, 'Flight Kochi → Delhi on 2025-11-21', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (429, 'Flight Delhi → Srinagar on 2026-01-08', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (430, 'Flight Lucknow → Mumbai on 2026-01-08', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (431, 'Flight Mumbai → Dubai on 2025-12-12', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (432, 'Flight Mumbai → Dubai on 2025-12-14', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (433, 'Flight Mumbai → Bangalore on 2026-01-05', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (434, 'Flight Mumbai → Bangalore on 2025-11-22', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (435, 'Flight Kochi → Delhi on 2025-12-25', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (436, 'Flight Mumbai → New York on 2026-01-02', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (437, 'Flight Kochi → Delhi on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (438, 'Flight Kochi → Delhi on 2026-01-22', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (439, 'Flight Mumbai → Dubai on 2025-12-22', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (440, 'Flight Lucknow → Mumbai on 2026-02-04', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (441, 'Flight Bangalore → Hyderabad on 2025-11-25', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (442, 'Flight Chennai → Kolkata on 2026-01-19', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (443, 'Flight Jaipur → Mumbai on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (444, 'Flight Jaipur → Mumbai on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (445, 'Flight Kochi → Delhi on 2025-12-05', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (446, 'Flight Delhi → Goa on 2025-12-11', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (447, 'Flight Delhi → Mumbai on 2025-11-19', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (448, 'Flight Ahmedabad → Bangalore on 2025-12-21', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (449, 'Flight Delhi → Srinagar on 2026-02-04', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (450, 'Flight Bangalore → Hyderabad on 2025-12-10', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (451, 'Flight Delhi → Srinagar on 2026-02-09', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (452, 'Flight Pune → Delhi on 2025-11-17', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (453, 'Flight Kochi → Delhi on 2025-12-09', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (454, 'Flight Pune → Delhi on 2026-01-09', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (455, 'Flight Delhi → Singapore on 2025-11-17', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (456, 'Flight Mumbai → New York on 2025-11-18', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (457, 'Flight Jaipur → Mumbai on 2025-11-28', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (458, 'Flight Bangalore → Hyderabad on 2025-12-14', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (459, 'Flight Bangalore → Hyderabad on 2026-01-06', 'Travel', 'Flights', 'One-way flight from Bangalore to Hyderabad');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (460, 'Flight Mumbai → Bangalore on 2025-12-02', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (461, 'Flight Chennai → Kolkata on 2026-01-29', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (462, 'Flight Chennai → Kolkata on 2026-02-08', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (463, 'Flight Bangalore → London on 2026-01-15', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (464, 'Flight Pune → Delhi on 2026-01-20', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (465, 'Flight Delhi → Goa on 2025-12-12', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (466, 'Flight Delhi → Goa on 2026-02-10', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (467, 'Flight Delhi → Srinagar on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (468, 'Flight Kochi → Delhi on 2025-12-16', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (469, 'Flight Mumbai → New York on 2026-02-03', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (470, 'Flight Delhi → Mumbai on 2025-12-10', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (471, 'Flight Ahmedabad → Bangalore on 2025-12-28', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (472, 'Flight Delhi → Srinagar on 2025-12-27', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (473, 'Flight Mumbai → Dubai on 2025-12-18', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (474, 'Flight Ahmedabad → Bangalore on 2025-12-02', 'Travel', 'Flights', 'One-way flight from Ahmedabad to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (475, 'Flight Kochi → Delhi on 2025-12-20', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (476, 'Flight Lucknow → Mumbai on 2026-01-06', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (477, 'Flight Mumbai → Dubai on 2025-12-29', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (478, 'Flight Chennai → Kolkata on 2026-01-22', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (479, 'Flight Mumbai → New York on 2025-12-23', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (480, 'Flight Bangalore → London on 2026-01-27', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (481, 'Flight Bangalore → London on 2025-11-22', 'Travel', 'Flights', 'One-way flight from Bangalore to London');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (482, 'Flight Chennai → Kolkata on 2026-01-15', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (483, 'Flight Delhi → Mumbai on 2025-12-06', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (484, 'Flight Jaipur → Mumbai on 2026-01-27', 'Travel', 'Flights', 'One-way flight from Jaipur to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (485, 'Flight Delhi → Mumbai on 2026-01-25', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (486, 'Flight Mumbai → Dubai on 2025-12-30', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (487, 'Flight Delhi → Srinagar on 2026-01-14', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (488, 'Flight Mumbai → Dubai on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (489, 'Flight Delhi → Singapore on 2026-02-02', 'Travel', 'Flights', 'One-way flight from Delhi to Singapore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (490, 'Flight Delhi → Srinagar on 2026-01-31', 'Travel', 'Flights', 'One-way flight from Delhi to Srinagar');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (491, 'Flight Mumbai → Dubai on 2026-01-09', 'Travel', 'Flights', 'One-way flight from Mumbai to Dubai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (492, 'Flight Kochi → Delhi on 2025-12-11', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (493, 'Flight Mumbai → Bangalore on 2026-01-07', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (494, 'Flight Lucknow → Mumbai on 2026-01-28', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (495, 'Flight Delhi → Mumbai on 2025-11-18', 'Travel', 'Flights', 'One-way flight from Delhi to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (496, 'Flight Mumbai → New York on 2026-01-01', 'Travel', 'Flights', 'One-way flight from Mumbai to New York');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (497, 'Flight Lucknow → Mumbai on 2025-12-01', 'Travel', 'Flights', 'One-way flight from Lucknow to Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (498, 'Flight Delhi → Goa on 2025-11-27', 'Travel', 'Flights', 'One-way flight from Delhi to Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (499, 'Flight Mumbai → Bangalore on 2026-01-10', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (500, 'Flight Pune → Delhi on 2025-12-11', 'Travel', 'Flights', 'One-way flight from Pune to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (501, 'Flight Mumbai → Bangalore on 2025-11-27', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (502, 'Flight Kochi → Delhi on 2025-12-20', 'Travel', 'Flights', 'One-way flight from Kochi to Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (503, 'Flight Mumbai → Bangalore on 2026-01-02', 'Travel', 'Flights', 'One-way flight from Mumbai to Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (504, 'Flight Chennai → Kolkata on 2025-12-31', 'Travel', 'Flights', 'One-way flight from Chennai to Kolkata');

-- Hotel Bookings (200)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (505, 'Taj Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (506, 'Holiday Inn Kerala - Suite', 'Travel', 'Hotels', 'Suite at Holiday Inn in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (507, 'Holiday Inn Udaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (508, 'Radisson Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (509, 'Hilton Jaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hilton in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (510, 'ITC Shimla - Suite', 'Travel', 'Hotels', 'Suite at ITC in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (511, 'Marriott Ooty - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (512, 'Oberoi Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (513, 'Hilton Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (514, 'ITC Mumbai - Suite', 'Travel', 'Hotels', 'Suite at ITC in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (515, 'ITC Ooty - Suite', 'Travel', 'Hotels', 'Suite at ITC in Ooty');
