-- Part 2: Products (501-1000+)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (516, 'Hilton Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (517, 'ITC Kerala - Executive Room', 'Travel', 'Hotels', 'Executive Room at ITC in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (518, 'Taj Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (519, 'Taj Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at Taj in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (520, 'Hyatt Bangalore - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hyatt in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (521, 'Holiday Inn Mumbai - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (522, 'Oberoi Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (523, 'Holiday Inn Ooty - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (524, 'Hyatt Udaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hyatt in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (525, 'ITC Shimla - Suite', 'Travel', 'Hotels', 'Suite at ITC in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (526, 'Holiday Inn Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (527, 'Taj Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (528, 'Oberoi Ooty - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (529, 'Oberoi Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (530, 'Hyatt Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hyatt in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (531, 'Marriott Kerala - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (532, 'Taj Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Taj in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (533, 'Oberoi Jaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (534, 'Radisson Bangalore - Suite', 'Travel', 'Hotels', 'Suite at Radisson in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (535, 'Marriott Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (536, 'Oberoi Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (537, 'Radisson Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (538, 'Marriott Shimla - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (539, 'Oberoi Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (540, 'Marriott Bangalore - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (541, 'Hyatt Shimla - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (542, 'Oberoi Jaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (543, 'Radisson Ooty - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (544, 'Marriott Manali - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (545, 'Hyatt Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hyatt in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (546, 'Taj Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Taj in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (547, 'Hilton Ooty - Suite', 'Travel', 'Hotels', 'Suite at Hilton in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (548, 'Marriott Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (549, 'ITC Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (550, 'Oberoi Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Oberoi in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (551, 'Holiday Inn Jaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (552, 'Taj Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (553, 'Holiday Inn Udaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (554, 'Oberoi Goa - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (555, 'Marriott Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (556, 'Marriott Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (557, 'Marriott Jaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (558, 'Radisson Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Radisson in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (559, 'ITC Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at ITC in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (560, 'Radisson Delhi - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (561, 'Radisson Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Radisson in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (562, 'Marriott Udaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (563, 'ITC Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at ITC in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (564, 'Hyatt Kerala - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hyatt in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (565, 'Taj Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (566, 'Hyatt Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hyatt in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (567, 'ITC Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at ITC in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (568, 'Taj Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (569, 'Hyatt Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hyatt in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (570, 'Taj Shimla - Suite', 'Travel', 'Hotels', 'Suite at Taj in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (571, 'Radisson Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (572, 'Oberoi Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (573, 'Taj Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (574, 'Hilton Delhi - Suite', 'Travel', 'Hotels', 'Suite at Hilton in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (575, 'Oberoi Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Oberoi in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (576, 'Taj Bangalore - Premium Room', 'Travel', 'Hotels', 'Premium Room at Taj in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (577, 'ITC Ooty - Suite', 'Travel', 'Hotels', 'Suite at ITC in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (578, 'Hilton Udaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hilton in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (579, 'Radisson Mumbai - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (580, 'Hyatt Manali - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (581, 'Holiday Inn Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Holiday Inn in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (582, 'Hilton Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (583, 'Marriott Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (584, 'Marriott Jaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (585, 'Marriott Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (586, 'Hilton Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (587, 'Oberoi Ooty - Executive Room', 'Travel', 'Hotels', 'Executive Room at Oberoi in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (588, 'Oberoi Manali - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (589, 'Marriott Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (590, 'Holiday Inn Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (591, 'ITC Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (592, 'Holiday Inn Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at Holiday Inn in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (593, 'Holiday Inn Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at Holiday Inn in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (594, 'Marriott Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (595, 'Hyatt Manali - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (596, 'Holiday Inn Udaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (597, 'Hyatt Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hyatt in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (598, 'Radisson Udaipur - Suite', 'Travel', 'Hotels', 'Suite at Radisson in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (599, 'Holiday Inn Delhi - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (600, 'Taj Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (601, 'Oberoi Bangalore - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (602, 'Oberoi Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Oberoi in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (603, 'Marriott Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (604, 'Oberoi Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (605, 'Radisson Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (606, 'Radisson Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at Radisson in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (607, 'Hyatt Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hyatt in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (608, 'Hilton Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (609, 'Hilton Shimla - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (610, 'Oberoi Udaipur - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (611, 'Marriott Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (612, 'Oberoi Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (613, 'Oberoi Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (614, 'Taj Delhi - Suite', 'Travel', 'Hotels', 'Suite at Taj in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (615, 'Taj Udaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (616, 'Hyatt Kerala - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hyatt in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (617, 'ITC Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (618, 'Marriott Goa - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (619, 'Marriott Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (620, 'ITC Kerala - Executive Room', 'Travel', 'Hotels', 'Executive Room at ITC in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (621, 'Hyatt Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (622, 'Holiday Inn Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (623, 'ITC Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (624, 'Holiday Inn Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (625, 'Holiday Inn Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (626, 'Oberoi Udaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (627, 'Marriott Kerala - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (628, 'Marriott Ooty - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (629, 'Taj Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (630, 'Hilton Udaipur - Suite', 'Travel', 'Hotels', 'Suite at Hilton in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (631, 'ITC Delhi - Executive Room', 'Travel', 'Hotels', 'Executive Room at ITC in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (632, 'Holiday Inn Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Holiday Inn in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (633, 'Taj Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Taj in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (634, 'Oberoi Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (635, 'Hyatt Goa - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (636, 'ITC Mumbai - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (637, 'Radisson Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (638, 'Hyatt Mumbai - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hyatt in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (639, 'ITC Goa - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at ITC in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (640, 'Hilton Goa - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hilton in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (641, 'Marriott Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (642, 'Taj Delhi - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (643, 'Hilton Udaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hilton in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (644, 'Hilton Delhi - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (645, 'Hyatt Manali - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hyatt in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (646, 'Hilton Delhi - Suite', 'Travel', 'Hotels', 'Suite at Hilton in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (647, 'Radisson Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (648, 'Marriott Delhi - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (649, 'Taj Jaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Taj in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (650, 'Taj Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (651, 'Hyatt Ooty - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (652, 'ITC Delhi - Executive Room', 'Travel', 'Hotels', 'Executive Room at ITC in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (653, 'Taj Delhi - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (654, 'Marriott Mumbai - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (655, 'Oberoi Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Oberoi in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (656, 'Holiday Inn Delhi - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Holiday Inn in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (657, 'Radisson Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Radisson in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (658, 'Oberoi Kerala - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (659, 'Hilton Delhi - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (660, 'Taj Udaipur - Suite', 'Travel', 'Hotels', 'Suite at Taj in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (661, 'ITC Goa - Suite', 'Travel', 'Hotels', 'Suite at ITC in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (662, 'Radisson Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (663, 'Taj Ooty - Suite', 'Travel', 'Hotels', 'Suite at Taj in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (664, 'Marriott Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (665, 'Holiday Inn Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at Holiday Inn in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (666, 'Oberoi Jaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Oberoi in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (667, 'Marriott Manali - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (668, 'Hyatt Delhi - Suite', 'Travel', 'Hotels', 'Suite at Hyatt in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (669, 'Radisson Udaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at Radisson in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (670, 'Oberoi Delhi - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (671, 'Holiday Inn Goa - Premium Room', 'Travel', 'Hotels', 'Premium Room at Holiday Inn in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (672, 'Taj Goa - Suite', 'Travel', 'Hotels', 'Suite at Taj in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (673, 'Hilton Shimla - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (674, 'Radisson Goa - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (675, 'Hilton Shimla - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hilton in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (676, 'Taj Kerala - Suite', 'Travel', 'Hotels', 'Suite at Taj in Kerala');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (677, 'Hilton Bangalore - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hilton in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (678, 'Hilton Ooty - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Hilton in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (679, 'Radisson Bangalore - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Radisson in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (680, 'ITC Udaipur - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (681, 'Hyatt Bangalore - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hyatt in Bangalore');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (682, 'ITC Ooty - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at ITC in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (683, 'Radisson Manali - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (684, 'Marriott Shimla - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (685, 'Oberoi Delhi - Suite', 'Travel', 'Hotels', 'Suite at Oberoi in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (686, 'ITC Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at ITC in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (687, 'Taj Jaipur - Suite', 'Travel', 'Hotels', 'Suite at Taj in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (688, 'Radisson Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (689, 'Radisson Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Radisson in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (690, 'ITC Jaipur - Suite', 'Travel', 'Hotels', 'Suite at ITC in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (691, 'Marriott Delhi - Premium Room', 'Travel', 'Hotels', 'Premium Room at Marriott in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (692, 'Taj Mumbai - Executive Room', 'Travel', 'Hotels', 'Executive Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (693, 'Taj Mumbai - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Taj in Mumbai');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (694, 'Marriott Ooty - Suite', 'Travel', 'Hotels', 'Suite at Marriott in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (695, 'Taj Shimla - Premium Room', 'Travel', 'Hotels', 'Premium Room at Taj in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (696, 'Hyatt Shimla - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hyatt in Shimla');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (697, 'Radisson Goa - Suite', 'Travel', 'Hotels', 'Suite at Radisson in Goa');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (698, 'Marriott Jaipur - Deluxe Room', 'Travel', 'Hotels', 'Deluxe Room at Marriott in Jaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (699, 'Radisson Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Radisson in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (700, 'Marriott Udaipur - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Udaipur');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (701, 'Taj Delhi - Suite', 'Travel', 'Hotels', 'Suite at Taj in Delhi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (702, 'Hyatt Ooty - Executive Room', 'Travel', 'Hotels', 'Executive Room at Hyatt in Ooty');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (703, 'Hilton Manali - Premium Room', 'Travel', 'Hotels', 'Premium Room at Hilton in Manali');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (704, 'Marriott Delhi - Executive Room', 'Travel', 'Hotels', 'Executive Room at Marriott in Delhi');

-- Fashion Items (100)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (705, 'Adidas Leggings', 'Fashion', 'Womens Wear', 'Adidas branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (706, 'Nike Leggings', 'Fashion', 'Womens Wear', 'Nike branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (707, 'Zara Jeans', 'Fashion', 'Mens Wear', 'Zara branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (708, 'Puma Jeans', 'Fashion', 'Mens Wear', 'Puma branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (709, 'Zara T-Shirt', 'Fashion', 'Mens Wear', 'Zara branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (710, 'Puma Saree', 'Fashion', 'Womens Wear', 'Puma branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (711, 'Adidas Kurti', 'Fashion', 'Womens Wear', 'Adidas branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (712, 'Levis Formal Trousers', 'Fashion', 'Mens Wear', 'Levis branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (713, 'Adidas Dress', 'Fashion', 'Womens Wear', 'Adidas branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (714, 'Nike Sneakers', 'Fashion', 'Footwear', 'Nike branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (715, 'Adidas Kurti', 'Fashion', 'Womens Wear', 'Adidas branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (716, 'Allen Solly Leggings', 'Fashion', 'Womens Wear', 'Allen Solly branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (717, 'Adidas Jeans', 'Fashion', 'Mens Wear', 'Adidas branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (718, 'Zara Sneakers', 'Fashion', 'Footwear', 'Zara branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (719, 'Nike Sneakers', 'Fashion', 'Footwear', 'Nike branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (720, 'H&M T-Shirt', 'Fashion', 'Mens Wear', 'H&M branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (721, 'Zara Dress', 'Fashion', 'Womens Wear', 'Zara branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (722, 'H&M Jeans', 'Fashion', 'Mens Wear', 'H&M branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (723, 'Allen Solly Kurti', 'Fashion', 'Womens Wear', 'Allen Solly branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (724, 'Levis Jeans', 'Fashion', 'Mens Wear', 'Levis branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (725, 'Levis Formal Shoes', 'Fashion', 'Footwear', 'Levis branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (726, 'H&M Kurti', 'Fashion', 'Womens Wear', 'H&M branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (727, 'H&M Leggings', 'Fashion', 'Womens Wear', 'H&M branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (728, 'Levis Formal Trousers', 'Fashion', 'Mens Wear', 'Levis branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (729, 'Nike Sneakers', 'Fashion', 'Footwear', 'Nike branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (730, 'Nike Dress', 'Fashion', 'Womens Wear', 'Nike branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (731, 'Nike Leggings', 'Fashion', 'Womens Wear', 'Nike branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (732, 'Puma T-Shirt', 'Fashion', 'Mens Wear', 'Puma branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (733, 'Adidas Formal Shoes', 'Fashion', 'Footwear', 'Adidas branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (734, 'Nike Saree', 'Fashion', 'Womens Wear', 'Nike branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (735, 'H&M Jeans', 'Fashion', 'Mens Wear', 'H&M branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (736, 'Nike Kurti', 'Fashion', 'Womens Wear', 'Nike branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (737, 'Zara Leggings', 'Fashion', 'Womens Wear', 'Zara branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (738, 'Zara Leggings', 'Fashion', 'Womens Wear', 'Zara branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (739, 'Nike Dress', 'Fashion', 'Womens Wear', 'Nike branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (740, 'Zara Formal Trousers', 'Fashion', 'Mens Wear', 'Zara branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (741, 'Nike Casual Shirt', 'Fashion', 'Mens Wear', 'Nike branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (742, 'Nike Casual Shirt', 'Fashion', 'Mens Wear', 'Nike branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (743, 'Adidas Saree', 'Fashion', 'Womens Wear', 'Adidas branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (744, 'Nike T-Shirt', 'Fashion', 'Mens Wear', 'Nike branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (745, 'Puma Formal Shoes', 'Fashion', 'Footwear', 'Puma branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (746, 'Zara Kurti', 'Fashion', 'Womens Wear', 'Zara branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (747, 'Adidas Casual Shirt', 'Fashion', 'Mens Wear', 'Adidas branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (748, 'Levis Casual Shirt', 'Fashion', 'Mens Wear', 'Levis branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (749, 'Puma Formal Shoes', 'Fashion', 'Footwear', 'Puma branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (750, 'Nike Formal Shoes', 'Fashion', 'Footwear', 'Nike branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (751, 'Van Heusen Leggings', 'Fashion', 'Womens Wear', 'Van Heusen branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (752, 'Adidas Dress', 'Fashion', 'Womens Wear', 'Adidas branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (753, 'Puma Formal Trousers', 'Fashion', 'Mens Wear', 'Puma branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (754, 'Nike Kurti', 'Fashion', 'Womens Wear', 'Nike branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (755, 'Adidas Kurti', 'Fashion', 'Womens Wear', 'Adidas branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (756, 'Puma Formal Trousers', 'Fashion', 'Mens Wear', 'Puma branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (757, 'Zara Saree', 'Fashion', 'Womens Wear', 'Zara branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (758, 'Van Heusen Kurti', 'Fashion', 'Womens Wear', 'Van Heusen branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (759, 'Zara Kurti', 'Fashion', 'Womens Wear', 'Zara branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (760, 'Puma Leggings', 'Fashion', 'Womens Wear', 'Puma branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (761, 'Puma Sneakers', 'Fashion', 'Footwear', 'Puma branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (762, 'Zara Saree', 'Fashion', 'Womens Wear', 'Zara branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (763, 'Nike Formal Trousers', 'Fashion', 'Mens Wear', 'Nike branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (764, 'Adidas Sneakers', 'Fashion', 'Footwear', 'Adidas branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (765, 'Levis Formal Shoes', 'Fashion', 'Footwear', 'Levis branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (766, 'Puma Sneakers', 'Fashion', 'Footwear', 'Puma branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (767, 'Zara Kurti', 'Fashion', 'Womens Wear', 'Zara branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (768, 'Allen Solly Formal Shoes', 'Fashion', 'Footwear', 'Allen Solly branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (769, 'H&M Formal Shoes', 'Fashion', 'Footwear', 'H&M branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (770, 'Nike Formal Trousers', 'Fashion', 'Mens Wear', 'Nike branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (771, 'Nike Kurti', 'Fashion', 'Womens Wear', 'Nike branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (772, 'Puma Kurti', 'Fashion', 'Womens Wear', 'Puma branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (773, 'Levis Casual Shirt', 'Fashion', 'Mens Wear', 'Levis branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (774, 'Adidas Saree', 'Fashion', 'Womens Wear', 'Adidas branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (775, 'Puma Formal Trousers', 'Fashion', 'Mens Wear', 'Puma branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (776, 'H&M Leggings', 'Fashion', 'Womens Wear', 'H&M branded Leggings');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (777, 'Van Heusen Kurti', 'Fashion', 'Womens Wear', 'Van Heusen branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (778, 'Zara Formal Trousers', 'Fashion', 'Mens Wear', 'Zara branded Formal Trousers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (779, 'Levis Jeans', 'Fashion', 'Mens Wear', 'Levis branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (780, 'Puma Formal Shoes', 'Fashion', 'Footwear', 'Puma branded Formal Shoes');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (781, 'Van Heusen Casual Shirt', 'Fashion', 'Mens Wear', 'Van Heusen branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (782, 'Zara Saree', 'Fashion', 'Womens Wear', 'Zara branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (783, 'Levis Kurti', 'Fashion', 'Womens Wear', 'Levis branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (784, 'H&M Sneakers', 'Fashion', 'Footwear', 'H&M branded Sneakers');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (785, 'Puma Kurti', 'Fashion', 'Womens Wear', 'Puma branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (786, 'Nike Dress', 'Fashion', 'Womens Wear', 'Nike branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (787, 'H&M Saree', 'Fashion', 'Womens Wear', 'H&M branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (788, 'Puma Kurti', 'Fashion', 'Womens Wear', 'Puma branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (789, 'Adidas Dress', 'Fashion', 'Womens Wear', 'Adidas branded Dress');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (790, 'Van Heusen Jeans', 'Fashion', 'Mens Wear', 'Van Heusen branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (791, 'Puma Kurti', 'Fashion', 'Womens Wear', 'Puma branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (792, 'Allen Solly Saree', 'Fashion', 'Womens Wear', 'Allen Solly branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (793, 'Nike Jeans', 'Fashion', 'Mens Wear', 'Nike branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (794, 'Puma Jeans', 'Fashion', 'Mens Wear', 'Puma branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (795, 'Puma T-Shirt', 'Fashion', 'Mens Wear', 'Puma branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (796, 'Puma Kurti', 'Fashion', 'Womens Wear', 'Puma branded Kurti');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (797, 'Adidas T-Shirt', 'Fashion', 'Mens Wear', 'Adidas branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (798, 'Allen Solly T-Shirt', 'Fashion', 'Mens Wear', 'Allen Solly branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (799, 'H&M Saree', 'Fashion', 'Womens Wear', 'H&M branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (800, 'Levis Jeans', 'Fashion', 'Mens Wear', 'Levis branded Jeans');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (801, 'Levis Saree', 'Fashion', 'Womens Wear', 'Levis branded Saree');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (802, 'H&M Casual Shirt', 'Fashion', 'Mens Wear', 'H&M branded Casual Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (803, 'Nike T-Shirt', 'Fashion', 'Mens Wear', 'Nike branded T-Shirt');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (804, 'Nike Sneakers', 'Fashion', 'Footwear', 'Nike branded Sneakers');

-- Home & Kitchen (100)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (805, 'Samsung Iron', 'Home & Kitchen', 'Appliances', 'Samsung Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (806, 'Godrej Air Conditioner', 'Home & Kitchen', 'Appliances', 'Godrej Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (807, 'Prestige Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Prestige Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (808, 'LG Pressure Cooker', 'Home & Kitchen', 'Appliances', 'LG Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (809, 'Prestige Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Prestige Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (810, 'Whirlpool Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Whirlpool Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (811, 'LG Curtains', 'Home & Kitchen', 'Appliances', 'LG Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (812, 'Whirlpool Washing Machine', 'Home & Kitchen', 'Appliances', 'Whirlpool Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (813, 'Godrej Iron', 'Home & Kitchen', 'Appliances', 'Godrej Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (814, 'Whirlpool Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Whirlpool Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (815, 'Samsung Curtains', 'Home & Kitchen', 'Appliances', 'Samsung Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (816, 'Godrej Iron', 'Home & Kitchen', 'Appliances', 'Godrej Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (817, 'Prestige Air Fryer', 'Home & Kitchen', 'Appliances', 'Prestige Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (818, 'Prestige Air Fryer', 'Home & Kitchen', 'Appliances', 'Prestige Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (819, 'Samsung Iron', 'Home & Kitchen', 'Appliances', 'Samsung Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (820, 'Philips Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Philips Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (821, 'Philips Washing Machine', 'Home & Kitchen', 'Appliances', 'Philips Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (822, 'Samsung Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Samsung Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (823, 'Whirlpool Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Whirlpool Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (824, 'Prestige Air Conditioner', 'Home & Kitchen', 'Appliances', 'Prestige Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (825, 'LG Washing Machine', 'Home & Kitchen', 'Appliances', 'LG Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (826, 'Samsung Bed Sheet Set', 'Home & Kitchen', 'Appliances', 'Samsung Bed Sheet Set for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (827, 'Prestige Air Fryer', 'Home & Kitchen', 'Appliances', 'Prestige Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (828, 'Bajaj Curtains', 'Home & Kitchen', 'Appliances', 'Bajaj Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (829, 'Philips Curtains', 'Home & Kitchen', 'Appliances', 'Philips Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (830, 'LG Washing Machine', 'Home & Kitchen', 'Appliances', 'LG Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (831, 'Bajaj Curtains', 'Home & Kitchen', 'Appliances', 'Bajaj Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (832, 'LG Bed Sheet Set', 'Home & Kitchen', 'Appliances', 'LG Bed Sheet Set for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (833, 'Whirlpool Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Whirlpool Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (834, 'Godrej Washing Machine', 'Home & Kitchen', 'Appliances', 'Godrej Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (835, 'Whirlpool Air Conditioner', 'Home & Kitchen', 'Appliances', 'Whirlpool Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (836, 'Whirlpool Air Conditioner', 'Home & Kitchen', 'Appliances', 'Whirlpool Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (837, 'Bajaj Mixer Grinder', 'Home & Kitchen', 'Appliances', 'Bajaj Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (838, 'Whirlpool Air Fryer', 'Home & Kitchen', 'Appliances', 'Whirlpool Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (839, 'Philips Iron', 'Home & Kitchen', 'Appliances', 'Philips Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (840, 'Bajaj Refrigerator', 'Home & Kitchen', 'Appliances', 'Bajaj Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (841, 'Prestige Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Prestige Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (842, 'LG Air Conditioner', 'Home & Kitchen', 'Appliances', 'LG Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (843, 'Samsung Curtains', 'Home & Kitchen', 'Appliances', 'Samsung Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (844, 'Whirlpool Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Whirlpool Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (845, 'Godrej Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Godrej Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (846, 'Whirlpool Refrigerator', 'Home & Kitchen', 'Appliances', 'Whirlpool Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (847, 'Prestige Curtains', 'Home & Kitchen', 'Appliances', 'Prestige Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (848, 'Godrej Washing Machine', 'Home & Kitchen', 'Appliances', 'Godrej Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (849, 'Whirlpool Curtains', 'Home & Kitchen', 'Appliances', 'Whirlpool Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (850, 'Whirlpool Mixer Grinder', 'Home & Kitchen', 'Appliances', 'Whirlpool Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (851, 'LG Refrigerator', 'Home & Kitchen', 'Appliances', 'LG Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (852, 'LG Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'LG Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (853, 'Philips Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Philips Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (854, 'Philips Washing Machine', 'Home & Kitchen', 'Appliances', 'Philips Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (855, 'Philips Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Philips Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (856, 'Philips Microwave Oven', 'Home & Kitchen', 'Appliances', 'Philips Microwave Oven for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (857, 'Philips Refrigerator', 'Home & Kitchen', 'Appliances', 'Philips Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (858, 'Prestige Refrigerator', 'Home & Kitchen', 'Appliances', 'Prestige Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (859, 'Prestige Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Prestige Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (860, 'Bajaj Water Purifier', 'Home & Kitchen', 'Appliances', 'Bajaj Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (861, 'Philips Washing Machine', 'Home & Kitchen', 'Appliances', 'Philips Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (862, 'Godrej Iron', 'Home & Kitchen', 'Appliances', 'Godrej Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (863, 'Philips Air Fryer', 'Home & Kitchen', 'Appliances', 'Philips Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (864, 'Philips Iron', 'Home & Kitchen', 'Appliances', 'Philips Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (865, 'LG Curtains', 'Home & Kitchen', 'Appliances', 'LG Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (866, 'Prestige Water Purifier', 'Home & Kitchen', 'Appliances', 'Prestige Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (867, 'Whirlpool Air Fryer', 'Home & Kitchen', 'Appliances', 'Whirlpool Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (868, 'Samsung Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Samsung Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (869, 'Philips Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Philips Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (870, 'Philips Air Conditioner', 'Home & Kitchen', 'Appliances', 'Philips Air Conditioner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (871, 'Philips Washing Machine', 'Home & Kitchen', 'Appliances', 'Philips Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (872, 'Samsung Washing Machine', 'Home & Kitchen', 'Appliances', 'Samsung Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (873, 'Prestige Iron', 'Home & Kitchen', 'Appliances', 'Prestige Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (874, 'Whirlpool Water Purifier', 'Home & Kitchen', 'Appliances', 'Whirlpool Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (875, 'Godrej Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Godrej Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (876, 'Samsung Refrigerator', 'Home & Kitchen', 'Appliances', 'Samsung Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (877, 'Whirlpool Washing Machine', 'Home & Kitchen', 'Appliances', 'Whirlpool Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (878, 'Prestige Refrigerator', 'Home & Kitchen', 'Appliances', 'Prestige Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (879, 'Godrej Water Purifier', 'Home & Kitchen', 'Appliances', 'Godrej Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (880, 'Prestige Iron', 'Home & Kitchen', 'Appliances', 'Prestige Iron for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (881, 'LG Curtains', 'Home & Kitchen', 'Appliances', 'LG Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (882, 'Bajaj Refrigerator', 'Home & Kitchen', 'Appliances', 'Bajaj Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (883, 'LG Washing Machine', 'Home & Kitchen', 'Appliances', 'LG Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (884, 'Samsung Washing Machine', 'Home & Kitchen', 'Appliances', 'Samsung Washing Machine for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (885, 'Philips Water Purifier', 'Home & Kitchen', 'Appliances', 'Philips Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (886, 'LG Refrigerator', 'Home & Kitchen', 'Appliances', 'LG Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (887, 'Whirlpool Bed Sheet Set', 'Home & Kitchen', 'Appliances', 'Whirlpool Bed Sheet Set for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (888, 'Prestige Mixer Grinder', 'Home & Kitchen', 'Appliances', 'Prestige Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (889, 'Whirlpool Air Fryer', 'Home & Kitchen', 'Appliances', 'Whirlpool Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (890, 'Prestige Microwave Oven', 'Home & Kitchen', 'Appliances', 'Prestige Microwave Oven for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (891, 'Philips Air Fryer', 'Home & Kitchen', 'Appliances', 'Philips Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (892, 'LG Mixer Grinder', 'Home & Kitchen', 'Appliances', 'LG Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (893, 'Bajaj Refrigerator', 'Home & Kitchen', 'Appliances', 'Bajaj Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (894, 'Whirlpool Microwave Oven', 'Home & Kitchen', 'Appliances', 'Whirlpool Microwave Oven for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (895, 'Samsung Air Fryer', 'Home & Kitchen', 'Appliances', 'Samsung Air Fryer for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (896, 'Godrej Mixer Grinder', 'Home & Kitchen', 'Appliances', 'Godrej Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (897, 'LG Mixer Grinder', 'Home & Kitchen', 'Appliances', 'LG Mixer Grinder for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (898, 'Prestige Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Prestige Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (899, 'Philips Refrigerator', 'Home & Kitchen', 'Appliances', 'Philips Refrigerator for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (900, 'Bajaj Pressure Cooker', 'Home & Kitchen', 'Appliances', 'Bajaj Pressure Cooker for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (901, 'Philips Vacuum Cleaner', 'Home & Kitchen', 'Appliances', 'Philips Vacuum Cleaner for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (902, 'Samsung Curtains', 'Home & Kitchen', 'Appliances', 'Samsung Curtains for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (903, 'Prestige Water Purifier', 'Home & Kitchen', 'Appliances', 'Prestige Water Purifier for home use');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (904, 'LG Iron', 'Home & Kitchen', 'Appliances', 'LG Iron for home use');

-- Books (50)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (905, 'The White Tiger', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (906, 'Midnight Children', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (907, 'Midnight Children', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (908, 'Wings of Fire', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (909, 'Revolution 2020', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (910, 'The White Tiger', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (911, 'A Suitable Boy', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (912, 'Wings of Fire', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (913, 'The Immortals of Meluha', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (914, 'Book Title 10', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (915, 'Book Title 11', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (916, 'Book Title 12', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (917, 'Book Title 13', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (918, 'Book Title 14', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (919, 'Book Title 15', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (920, 'Book Title 16', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (921, 'Book Title 17', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (922, 'Book Title 18', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (923, 'Book Title 19', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (924, 'Book Title 20', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (925, 'Book Title 21', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (926, 'Book Title 22', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (927, 'Book Title 23', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (928, 'Book Title 24', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (929, 'Book Title 25', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (930, 'Book Title 26', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (931, 'Book Title 27', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (932, 'Book Title 28', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (933, 'Book Title 29', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (934, 'Book Title 30', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (935, 'Book Title 31', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (936, 'Book Title 32', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (937, 'Book Title 33', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (938, 'Book Title 34', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (939, 'Book Title 35', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (940, 'Book Title 36', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (941, 'Book Title 37', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (942, 'Book Title 38', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (943, 'Book Title 39', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (944, 'Book Title 40', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (945, 'Book Title 41', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (946, 'Book Title 42', 'Books', 'Fiction', 'Book by Chetan Bhagat');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (947, 'Book Title 43', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (948, 'Book Title 44', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (949, 'Book Title 45', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (950, 'Book Title 46', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (951, 'Book Title 47', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (952, 'Book Title 48', 'Books', 'Fiction', 'Book by Amish Tripathi');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (953, 'Book Title 49', 'Books', 'Fiction', 'Book by R.K. Narayan');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (954, 'Book Title 50', 'Books', 'Fiction', 'Book by Amish Tripathi');

-- Sports & Fitness (50)
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (955, 'Cosco Resistance Bands', 'Sports', 'Fitness', 'Cosco Resistance Bands for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (956, 'Cosco Treadmill', 'Sports', 'Fitness', 'Cosco Treadmill for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (957, 'Puma Treadmill', 'Sports', 'Fitness', 'Puma Treadmill for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (958, 'Reebok Resistance Bands', 'Sports', 'Fitness', 'Reebok Resistance Bands for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (959, 'Adidas Cricket Bat', 'Sports', 'Fitness', 'Adidas Cricket Bat for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (960, 'Decathlon Tennis Racket', 'Sports', 'Fitness', 'Decathlon Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (961, 'Reebok Dumbbell Set', 'Sports', 'Fitness', 'Reebok Dumbbell Set for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (962, 'Cosco Treadmill', 'Sports', 'Fitness', 'Cosco Treadmill for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (963, 'Decathlon Gym Bag', 'Sports', 'Fitness', 'Decathlon Gym Bag for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (964, 'Adidas Tennis Racket', 'Sports', 'Fitness', 'Adidas Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (965, 'Adidas Dumbbell Set', 'Sports', 'Fitness', 'Adidas Dumbbell Set for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (966, 'Reebok Football', 'Sports', 'Fitness', 'Reebok Football for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (967, 'Reebok Dumbbell Set', 'Sports', 'Fitness', 'Reebok Dumbbell Set for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (968, 'Reebok Protein Supplement', 'Sports', 'Fitness', 'Reebok Protein Supplement for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (969, 'Puma Sports Shoes', 'Sports', 'Fitness', 'Puma Sports Shoes for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (970, 'Reebok Badminton Racket', 'Sports', 'Fitness', 'Reebok Badminton Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (971, 'Cosco Gym Bag', 'Sports', 'Fitness', 'Cosco Gym Bag for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (972, 'Puma Tennis Racket', 'Sports', 'Fitness', 'Puma Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (973, 'Reebok Sports Shoes', 'Sports', 'Fitness', 'Reebok Sports Shoes for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (974, 'Nike Protein Supplement', 'Sports', 'Fitness', 'Nike Protein Supplement for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (975, 'Adidas Tennis Racket', 'Sports', 'Fitness', 'Adidas Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (976, 'Adidas Cricket Bat', 'Sports', 'Fitness', 'Adidas Cricket Bat for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (977, 'Reebok Yoga Mat', 'Sports', 'Fitness', 'Reebok Yoga Mat for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (978, 'Nike Gym Bag', 'Sports', 'Fitness', 'Nike Gym Bag for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (979, 'Adidas Sports Shoes', 'Sports', 'Fitness', 'Adidas Sports Shoes for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (980, 'Cosco Fitness Tracker', 'Sports', 'Fitness', 'Cosco Fitness Tracker for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (981, 'Adidas Tennis Racket', 'Sports', 'Fitness', 'Adidas Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (982, 'Adidas Dumbbell Set', 'Sports', 'Fitness', 'Adidas Dumbbell Set for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (983, 'Cosco Treadmill', 'Sports', 'Fitness', 'Cosco Treadmill for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (984, 'Cosco Treadmill', 'Sports', 'Fitness', 'Cosco Treadmill for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (985, 'Decathlon Sports Shoes', 'Sports', 'Fitness', 'Decathlon Sports Shoes for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (986, 'Puma Badminton Racket', 'Sports', 'Fitness', 'Puma Badminton Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (987, 'Decathlon Resistance Bands', 'Sports', 'Fitness', 'Decathlon Resistance Bands for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (988, 'Adidas Protein Supplement', 'Sports', 'Fitness', 'Adidas Protein Supplement for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (989, 'Decathlon Fitness Tracker', 'Sports', 'Fitness', 'Decathlon Fitness Tracker for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (990, 'Nike Tennis Racket', 'Sports', 'Fitness', 'Nike Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (991, 'Adidas Yoga Mat', 'Sports', 'Fitness', 'Adidas Yoga Mat for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (992, 'Puma Badminton Racket', 'Sports', 'Fitness', 'Puma Badminton Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (993, 'Cosco Tennis Racket', 'Sports', 'Fitness', 'Cosco Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (994, 'Nike Protein Supplement', 'Sports', 'Fitness', 'Nike Protein Supplement for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (995, 'Adidas Dumbbell Set', 'Sports', 'Fitness', 'Adidas Dumbbell Set for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (996, 'Puma Yoga Mat', 'Sports', 'Fitness', 'Puma Yoga Mat for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (997, 'Puma Resistance Bands', 'Sports', 'Fitness', 'Puma Resistance Bands for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (998, 'Adidas Gym Bag', 'Sports', 'Fitness', 'Adidas Gym Bag for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (999, 'Decathlon Protein Supplement', 'Sports', 'Fitness', 'Decathlon Protein Supplement for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1000, 'Cosco Tennis Racket', 'Sports', 'Fitness', 'Cosco Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1001, 'Cosco Football', 'Sports', 'Fitness', 'Cosco Football for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1002, 'Decathlon Gym Bag', 'Sports', 'Fitness', 'Decathlon Gym Bag for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1003, 'Puma Tennis Racket', 'Sports', 'Fitness', 'Puma Tennis Racket for fitness');
INSERT INTO Products (ProductID, name, category, subCategory, description) VALUES (1004, 'Nike Football', 'Sports', 'Fitness', 'Nike Football for fitness');

-- Total Products Inserted: 1004

