-- Part 1: Credit Cards (1-250)
-- ========================================
-- 6. INSERT CREDIT CARDS (500)
-- ========================================

INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (1, 'Yes Bank', 'Cashback', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (2, 'IndusInd', 'MoneyBack', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (3, 'ICICI', 'Flipkart', 10.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (4, 'ICICI', 'AceCredit', 1.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (5, 'Standard Chartered', 'Amazon Pay', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (6, 'ICICI', 'SimplyCLICK', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (7, 'IDFC', 'Neo', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (8, 'Kotak', 'Cashback', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (9, 'Kotak', 'Diners Black', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (10, 'IndusInd', 'AceCredit', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (11, 'HDFC', 'Regalia', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (12, 'ICICI', 'AceCredit', 1.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (13, 'Axis', 'Regalia', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (14, 'Kotak', 'Titanium', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (15, 'Standard Chartered', 'MoneyBack', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (16, 'HDFC', 'Diners Black', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (17, 'IDFC', 'Diners Black', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (18, 'Yes Bank', 'Millennia', 10.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (19, 'Axis', 'Titanium', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (20, 'IDFC', 'Titanium', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (21, 'IndusInd', 'AceCredit', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (22, 'RBL', 'Neo', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (23, 'Yes Bank', 'Diners Black', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (24, 'Axis', 'Diners Black', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (25, 'IndusInd', 'Flipkart', 10.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (26, 'IndusInd', 'Amazon Pay', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (27, 'ICICI', 'AceCredit', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (28, 'SBI', 'Flipkart', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (29, 'HDFC', 'Titanium', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (30, 'Kotak', 'Regalia', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (31, 'HDFC', 'Gold', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (32, 'IDFC', 'Cashback', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (33, 'Standard Chartered', 'Flipkart', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (34, 'SBI', 'Regalia', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (35, 'IDFC', 'Neo', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (36, 'Kotak', 'Gold', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (37, 'RBL', 'Platinum', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (38, 'SBI', 'Diners Black', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (39, 'HDFC', 'Cashback', 3.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (40, 'SBI', 'Neo', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (41, 'Yes Bank', 'Millennia', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (42, 'IndusInd', 'MoneyBack', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (43, 'HDFC', 'Amazon Pay', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (44, 'SBI', 'Cashback', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (45, 'SBI', 'Millennia', 10.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (46, 'SBI', 'Diners Black', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (47, 'Yes Bank', 'MoneyBack', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (48, 'SBI', 'SimplyCLICK', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (49, 'IDFC', 'Regalia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (50, 'IndusInd', 'SimplyCLICK', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (51, 'IndusInd', 'Millennia', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (52, 'ICICI', 'Platinum', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (53, 'Kotak', 'SimplyCLICK', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (54, 'Standard Chartered', 'Titanium', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (55, 'Yes Bank', 'Amazon Pay', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (56, 'ICICI', 'AceCredit', 4.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (57, 'Axis', 'AceCredit', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (58, 'Standard Chartered', 'Neo', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (59, 'Yes Bank', 'MoneyBack', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (60, 'HDFC', 'Platinum', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (61, 'SBI', 'Cashback', 10.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (62, 'ICICI', 'Cashback', 5.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (63, 'RBL', 'Platinum', 5.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (64, 'Kotak', 'Cashback', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (65, 'Standard Chartered', 'Flipkart', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (66, 'SBI', 'Platinum', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (67, 'HDFC', 'Cashback', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (68, 'IndusInd', 'Cashback', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (69, 'SBI', 'SimplyCLICK', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (70, 'Standard Chartered', 'SimplyCLICK', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (71, 'Axis', 'Titanium', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (72, 'ICICI', 'Gold', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (73, 'IndusInd', 'Millennia', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (74, 'SBI', 'Gold', 10.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (75, 'Axis', 'Amazon Pay', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (76, 'RBL', 'MoneyBack', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (77, 'ICICI', 'SimplyCLICK', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (78, 'HDFC', 'Neo', 3.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (79, 'Axis', 'Millennia', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (80, 'RBL', 'Platinum', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (81, 'RBL', 'Millennia', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (82, 'SBI', 'Millennia', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (83, 'IDFC', 'Cashback', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (84, 'ICICI', 'SimplyCLICK', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (85, 'SBI', 'Regalia', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (86, 'IDFC', 'SimplyCLICK', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (87, 'ICICI', 'Neo', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (88, 'Axis', 'SimplyCLICK', 2.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (89, 'Standard Chartered', 'Amazon Pay', 4.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (90, 'RBL', 'Millennia', 10.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (91, 'Yes Bank', 'Gold', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (92, 'Axis', 'Gold', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (93, 'Yes Bank', 'AceCredit', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (94, 'IDFC', 'Millennia', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (95, 'RBL', 'Titanium', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (96, 'Axis', 'Regalia', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (97, 'Standard Chartered', 'Regalia', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (98, 'SBI', 'Regalia', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (99, 'SBI', 'Regalia', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (100, 'Kotak', 'Regalia', 5.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (101, 'Kotak', 'Neo', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (102, 'IndusInd', 'Millennia', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (103, 'Axis', 'Millennia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (104, 'RBL', 'Regalia', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (105, 'ICICI', 'Cashback', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (106, 'IndusInd', 'Neo', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (107, 'SBI', 'Platinum', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (108, 'IDFC', 'Amazon Pay', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (109, 'HDFC', 'Diners Black', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (110, 'IDFC', 'Gold', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (111, 'RBL', 'Millennia', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (112, 'IDFC', 'Diners Black', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (113, 'Kotak', 'Amazon Pay', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (114, 'IndusInd', 'AceCredit', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (115, 'Axis', 'Millennia', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (116, 'SBI', 'Diners Black', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (117, 'Axis', 'Diners Black', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (118, 'Yes Bank', 'AceCredit', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (119, 'Yes Bank', 'Gold', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (120, 'IDFC', 'Amazon Pay', 1.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (121, 'IDFC', 'MoneyBack', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (122, 'SBI', 'AceCredit', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (123, 'IndusInd', 'Titanium', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (124, 'Yes Bank', 'SimplyCLICK', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (125, 'IndusInd', 'Cashback', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (126, 'IndusInd', 'AceCredit', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (127, 'Standard Chartered', 'AceCredit', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (128, 'Kotak', 'Platinum', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (129, 'IDFC', 'Gold', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (130, 'IndusInd', 'Titanium', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (131, 'ICICI', 'MoneyBack', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (132, 'Kotak', 'Titanium', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (133, 'IndusInd', 'Titanium', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (134, 'SBI', 'AceCredit', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (135, 'RBL', 'Titanium', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (136, 'IDFC', 'Regalia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (137, 'Axis', 'Amazon Pay', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (138, 'SBI', 'Amazon Pay', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (139, 'IndusInd', 'Gold', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (140, 'Kotak', 'Platinum', 3.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (141, 'IDFC', 'AceCredit', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (142, 'IDFC', 'Millennia', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (143, 'Axis', 'Regalia', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (144, 'Axis', 'Amazon Pay', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (145, 'Axis', 'Millennia', 1.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (146, 'Axis', 'Flipkart', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (147, 'IndusInd', 'MoneyBack', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (148, 'Yes Bank', 'Flipkart', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (149, 'Yes Bank', 'Amazon Pay', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (150, 'Axis', 'Amazon Pay', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (151, 'SBI', 'Gold', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (152, 'Axis', 'Platinum', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (153, 'SBI', 'Diners Black', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (154, 'ICICI', 'Neo', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (155, 'Yes Bank', 'Neo', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (156, 'RBL', 'Amazon Pay', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (157, 'ICICI', 'Neo', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (158, 'Yes Bank', 'Gold', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (159, 'Kotak', 'Diners Black', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (160, 'Axis', 'Millennia', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (161, 'HDFC', 'Neo', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (162, 'IndusInd', 'Gold', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (163, 'Kotak', 'Cashback', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (164, 'IndusInd', 'Diners Black', 10.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (165, 'SBI', 'Neo', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (166, 'Axis', 'Amazon Pay', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (167, 'ICICI', 'Amazon Pay', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (168, 'HDFC', 'Millennia', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (169, 'Kotak', 'Cashback', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (170, 'Axis', 'Cashback', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (171, 'Standard Chartered', 'Platinum', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (172, 'Standard Chartered', 'Diners Black', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (173, 'ICICI', 'Titanium', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (174, 'Yes Bank', 'Millennia', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (175, 'Axis', 'MoneyBack', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (176, 'RBL', 'AceCredit', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (177, 'RBL', 'Gold', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (178, 'IDFC', 'Millennia', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (179, 'Kotak', 'Millennia', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (180, 'RBL', 'Millennia', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (181, 'Standard Chartered', 'MoneyBack', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (182, 'ICICI', 'Millennia', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (183, 'Axis', 'SimplyCLICK', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (184, 'SBI', 'Millennia', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (185, 'RBL', 'AceCredit', 1.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (186, 'ICICI', 'Millennia', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (187, 'Kotak', 'Cashback', 1.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (188, 'Yes Bank', 'Flipkart', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (189, 'RBL', 'Platinum', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (190, 'ICICI', 'Millennia', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (191, 'HDFC', 'Millennia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (192, 'HDFC', 'Regalia', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (193, 'Standard Chartered', 'Cashback', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (194, 'IndusInd', 'Regalia', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (195, 'RBL', 'Titanium', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (196, 'ICICI', 'Diners Black', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (197, 'ICICI', 'Amazon Pay', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (198, 'RBL', 'MoneyBack', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (199, 'Axis', 'Regalia', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (200, 'HDFC', 'Titanium', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (201, 'Yes Bank', 'Millennia', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (202, 'RBL', 'AceCredit', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (203, 'Yes Bank', 'Platinum', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (204, 'Axis', 'Platinum', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (205, 'IDFC', 'SimplyCLICK', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (206, 'IDFC', 'Cashback', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (207, 'ICICI', 'Platinum', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (208, 'SBI', 'Diners Black', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (209, 'IDFC', 'Titanium', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (210, 'Standard Chartered', 'Gold', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (211, 'IDFC', 'Amazon Pay', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (212, 'Axis', 'Cashback', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (213, 'Kotak', 'Flipkart', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (214, 'Kotak', 'Amazon Pay', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (215, 'IDFC', 'Regalia', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (216, 'Yes Bank', 'SimplyCLICK', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (217, 'RBL', 'Neo', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (218, 'HDFC', 'Millennia', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (219, 'Axis', 'Gold', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (220, 'IDFC', 'MoneyBack', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (221, 'ICICI', 'Gold', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (222, 'IDFC', 'Diners Black', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (223, 'RBL', 'Millennia', 10.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (224, 'IDFC', 'Platinum', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (225, 'Kotak', 'Cashback', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (226, 'IDFC', 'Neo', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (227, 'IndusInd', 'Regalia', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (228, 'Yes Bank', 'AceCredit', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (229, 'Yes Bank', 'Diners Black', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (230, 'Standard Chartered', 'Cashback', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (231, 'Yes Bank', 'Cashback', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (232, 'RBL', 'Regalia', 2.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (233, 'Kotak', 'AceCredit', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (234, 'ICICI', 'Platinum', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (235, 'Standard Chartered', 'Amazon Pay', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (236, 'ICICI', 'SimplyCLICK', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (237, 'Axis', 'Regalia', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (238, 'IndusInd', 'AceCredit', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (239, 'Kotak', 'SimplyCLICK', 10.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (240, 'RBL', 'Regalia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (241, 'IndusInd', 'Flipkart', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (242, 'Axis', 'Diners Black', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (243, 'RBL', 'MoneyBack', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (244, 'IDFC', 'Millennia', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (245, 'HDFC', 'Millennia', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (246, 'ICICI', 'SimplyCLICK', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (247, 'RBL', 'MoneyBack', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (248, 'Yes Bank', 'Gold', 2.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (249, 'IndusInd', 'Regalia', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (250, 'Kotak', 'Cashback', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (251, 'Yes Bank', 'Millennia', 5.0, 'Grocery');
