-- Part 2: Credit Cards (251-500)
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (252, 'Standard Chartered', 'Cashback', 4.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (253, 'RBL', 'Neo', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (254, 'Standard Chartered', 'Millennia', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (255, 'SBI', 'Diners Black', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (256, 'Axis', 'SimplyCLICK', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (257, 'Standard Chartered', 'SimplyCLICK', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (258, 'IndusInd', 'Regalia', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (259, 'IDFC', 'Cashback', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (260, 'Standard Chartered', 'SimplyCLICK', 4.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (261, 'IDFC', 'AceCredit', 10.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (262, 'SBI', 'Titanium', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (263, 'IndusInd', 'Neo', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (264, 'HDFC', 'SimplyCLICK', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (265, 'Kotak', 'Cashback', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (266, 'RBL', 'Neo', 1.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (267, 'Yes Bank', 'Regalia', 5.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (268, 'Kotak', 'Flipkart', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (269, 'Yes Bank', 'Flipkart', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (270, 'Standard Chartered', 'Cashback', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (271, 'IndusInd', 'Cashback', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (272, 'Kotak', 'Neo', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (273, 'IndusInd', 'SimplyCLICK', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (274, 'Kotak', 'SimplyCLICK', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (275, 'ICICI', 'Regalia', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (276, 'HDFC', 'Titanium', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (277, 'IDFC', 'Flipkart', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (278, 'Axis', 'Diners Black', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (279, 'Standard Chartered', 'Neo', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (280, 'IDFC', 'Gold', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (281, 'IndusInd', 'Cashback', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (282, 'IndusInd', 'Amazon Pay', 1.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (283, 'Kotak', 'MoneyBack', 3.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (284, 'IDFC', 'Cashback', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (285, 'Standard Chartered', 'SimplyCLICK', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (286, 'Kotak', 'SimplyCLICK', 2.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (287, 'HDFC', 'SimplyCLICK', 4.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (288, 'SBI', 'Titanium', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (289, 'Kotak', 'Diners Black', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (290, 'ICICI', 'MoneyBack', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (291, 'HDFC', 'Platinum', 10.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (292, 'Standard Chartered', 'Neo', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (293, 'Kotak', 'MoneyBack', 7.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (294, 'Axis', 'MoneyBack', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (295, 'HDFC', 'Diners Black', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (296, 'ICICI', 'Amazon Pay', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (297, 'Yes Bank', 'MoneyBack', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (298, 'HDFC', 'SimplyCLICK', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (299, 'IDFC', 'Millennia', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (300, 'Axis', 'MoneyBack', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (301, 'Standard Chartered', 'SimplyCLICK', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (302, 'ICICI', 'Gold', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (303, 'Axis', 'SimplyCLICK', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (304, 'IDFC', 'Diners Black', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (305, 'SBI', 'Gold', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (306, 'IndusInd', 'Amazon Pay', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (307, 'IDFC', 'Flipkart', 2.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (308, 'Axis', 'Regalia', 4.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (309, 'IndusInd', 'Millennia', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (310, 'SBI', 'Gold', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (311, 'Standard Chartered', 'SimplyCLICK', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (312, 'Kotak', 'SimplyCLICK', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (313, 'ICICI', 'Amazon Pay', 10.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (314, 'Axis', 'Regalia', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (315, 'SBI', 'Platinum', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (316, 'Yes Bank', 'Neo', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (317, 'Yes Bank', 'SimplyCLICK', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (318, 'Standard Chartered', 'SimplyCLICK', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (319, 'Standard Chartered', 'Flipkart', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (320, 'ICICI', 'Titanium', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (321, 'Standard Chartered', 'AceCredit', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (322, 'ICICI', 'Titanium', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (323, 'Yes Bank', 'AceCredit', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (324, 'IDFC', 'Millennia', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (325, 'ICICI', 'Flipkart', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (326, 'SBI', 'MoneyBack', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (327, 'IndusInd', 'SimplyCLICK', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (328, 'Kotak', 'SimplyCLICK', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (329, 'IDFC', 'AceCredit', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (330, 'Standard Chartered', 'AceCredit', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (331, 'HDFC', 'Millennia', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (332, 'Standard Chartered', 'SimplyCLICK', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (333, 'HDFC', 'AceCredit', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (334, 'SBI', 'Regalia', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (335, 'Kotak', 'Amazon Pay', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (336, 'Kotak', 'Titanium', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (337, 'Yes Bank', 'Diners Black', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (338, 'Yes Bank', 'Gold', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (339, 'RBL', 'Neo', 7.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (340, 'Standard Chartered', 'Diners Black', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (341, 'Kotak', 'Gold', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (342, 'Standard Chartered', 'Gold', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (343, 'Standard Chartered', 'Flipkart', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (344, 'Kotak', 'Millennia', 10.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (345, 'SBI', 'Neo', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (346, 'Axis', 'Neo', 1.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (347, 'Kotak', 'SimplyCLICK', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (348, 'IndusInd', 'MoneyBack', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (349, 'Standard Chartered', 'Diners Black', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (350, 'RBL', 'SimplyCLICK', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (351, 'ICICI', 'Millennia', 2.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (352, 'RBL', 'Regalia', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (353, 'SBI', 'Amazon Pay', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (354, 'HDFC', 'Titanium', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (355, 'Yes Bank', 'Cashback', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (356, 'Yes Bank', 'Flipkart', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (357, 'ICICI', 'Millennia', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (358, 'Standard Chartered', 'Titanium', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (359, 'Kotak', 'MoneyBack', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (360, 'SBI', 'Titanium', 1.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (361, 'ICICI', 'Regalia', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (362, 'Axis', 'Neo', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (363, 'Axis', 'Gold', 2.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (364, 'RBL', 'AceCredit', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (365, 'HDFC', 'Amazon Pay', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (366, 'RBL', 'Gold', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (367, 'SBI', 'SimplyCLICK', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (368, 'Kotak', 'Diners Black', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (369, 'Yes Bank', 'SimplyCLICK', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (370, 'SBI', 'Regalia', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (371, 'Kotak', 'MoneyBack', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (372, 'Yes Bank', 'SimplyCLICK', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (373, 'Standard Chartered', 'SimplyCLICK', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (374, 'HDFC', 'Platinum', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (375, 'Axis', 'SimplyCLICK', 10.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (376, 'Standard Chartered', 'Cashback', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (377, 'IDFC', 'Flipkart', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (378, 'Standard Chartered', 'Diners Black', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (379, 'Yes Bank', 'Flipkart', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (380, 'IDFC', 'AceCredit', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (381, 'HDFC', 'Cashback', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (382, 'Kotak', 'Cashback', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (383, 'Standard Chartered', 'Regalia', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (384, 'IndusInd', 'Amazon Pay', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (385, 'Standard Chartered', 'Cashback', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (386, 'RBL', 'Titanium', 5.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (387, 'RBL', 'Platinum', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (388, 'ICICI', 'Neo', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (389, 'IDFC', 'Millennia', 3.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (390, 'Standard Chartered', 'Amazon Pay', 3.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (391, 'IndusInd', 'Neo', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (392, 'Standard Chartered', 'Gold', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (393, 'Axis', 'Millennia', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (394, 'IDFC', 'Diners Black', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (395, 'Standard Chartered', 'Diners Black', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (396, 'Kotak', 'Amazon Pay', 3.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (397, 'IndusInd', 'AceCredit', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (398, 'IndusInd', 'SimplyCLICK', 7.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (399, 'RBL', 'MoneyBack', 2.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (400, 'HDFC', 'SimplyCLICK', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (401, 'RBL', 'Cashback', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (402, 'SBI', 'Diners Black', 5.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (403, 'IDFC', 'MoneyBack', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (404, 'Yes Bank', 'SimplyCLICK', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (405, 'Yes Bank', 'Millennia', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (406, 'Kotak', 'MoneyBack', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (407, 'Axis', 'Diners Black', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (408, 'IDFC', 'Amazon Pay', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (409, 'RBL', 'Diners Black', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (410, 'Axis', 'Gold', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (411, 'SBI', 'Platinum', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (412, 'Yes Bank', 'MoneyBack', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (413, 'IndusInd', 'Millennia', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (414, 'HDFC', 'MoneyBack', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (415, 'ICICI', 'Regalia', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (416, 'Kotak', 'MoneyBack', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (417, 'Yes Bank', 'AceCredit', 2.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (418, 'RBL', 'Neo', 10.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (419, 'IndusInd', 'Regalia', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (420, 'SBI', 'AceCredit', 2.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (421, 'Axis', 'Flipkart', 2.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (422, 'SBI', 'Amazon Pay', 4.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (423, 'Axis', 'Titanium', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (424, 'SBI', 'SimplyCLICK', 4.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (425, 'IDFC', 'Regalia', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (426, 'Standard Chartered', 'Gold', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (427, 'Kotak', 'Cashback', 1.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (428, 'IDFC', 'MoneyBack', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (429, 'Axis', 'Amazon Pay', 2.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (430, 'SBI', 'SimplyCLICK', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (431, 'Yes Bank', 'Amazon Pay', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (432, 'IndusInd', 'Diners Black', 3.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (433, 'ICICI', 'Titanium', 5.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (434, 'Standard Chartered', 'Cashback', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (435, 'Axis', 'Platinum', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (436, 'IDFC', 'AceCredit', 1.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (437, 'Axis', 'Gold', 7.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (438, 'Axis', 'MoneyBack', 3.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (439, 'HDFC', 'Gold', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (440, 'Axis', 'Diners Black', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (441, 'ICICI', 'SimplyCLICK', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (442, 'SBI', 'Gold', 5.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (443, 'SBI', 'AceCredit', 10.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (444, 'IDFC', 'Regalia', 10.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (445, 'IndusInd', 'Amazon Pay', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (446, 'Axis', 'Neo', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (447, 'SBI', 'Flipkart', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (448, 'ICICI', 'Titanium', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (449, 'Yes Bank', 'Cashback', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (450, 'Axis', 'Platinum', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (451, 'IndusInd', 'Regalia', 1.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (452, 'IDFC', 'SimplyCLICK', 2.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (453, 'Kotak', 'Gold', 5.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (454, 'RBL', 'Diners Black', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (455, 'Yes Bank', 'Millennia', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (456, 'HDFC', 'Platinum', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (457, 'IndusInd', 'Amazon Pay', 1.5, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (458, 'Kotak', 'Cashback', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (459, 'Axis', 'Gold', 4.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (460, 'Yes Bank', 'Regalia', 7.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (461, 'Standard Chartered', 'Gold', 1.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (462, 'RBL', 'Cashback', 2.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (463, 'ICICI', 'Regalia', 5.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (464, 'Kotak', 'AceCredit', 1.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (465, 'Yes Bank', 'MoneyBack', 2.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (466, 'RBL', 'Cashback', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (467, 'Kotak', 'MoneyBack', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (468, 'RBL', 'Gold', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (469, 'IndusInd', 'Diners Black', 4.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (470, 'IDFC', 'Cashback', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (471, 'IDFC', 'Gold', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (472, 'ICICI', 'SimplyCLICK', 2.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (473, 'SBI', 'Platinum', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (474, 'IndusInd', 'Amazon Pay', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (475, 'Axis', 'MoneyBack', 1.5, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (476, 'IDFC', 'Gold', 1.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (477, 'Standard Chartered', 'Millennia', 4.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (478, 'Yes Bank', 'AceCredit', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (479, 'RBL', 'Platinum', 1.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (480, 'RBL', 'Neo', 5.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (481, 'RBL', 'Gold', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (482, 'ICICI', 'Amazon Pay', 2.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (483, 'ICICI', 'Cashback', 10.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (484, 'ICICI', 'AceCredit', 1.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (485, 'RBL', 'Regalia', 10.0, 'Shopping');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (486, 'Standard Chartered', 'SimplyCLICK', 2.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (487, 'HDFC', 'Millennia', 1.5, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (488, 'IDFC', 'Millennia', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (489, 'Yes Bank', 'Millennia', 10.0, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (490, 'Axis', 'Flipkart', 7.5, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (491, 'IDFC', 'MoneyBack', 1.0, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (492, 'SBI', 'Gold', 5.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (493, 'IDFC', 'SimplyCLICK', 1.0, 'Grocery');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (494, 'ICICI', 'Millennia', 5.0, 'Dining');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (495, 'Axis', 'Diners Black', 7.5, 'Travel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (496, 'IndusInd', 'Millennia', 4.0, 'Fuel');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (497, 'SBI', 'Titanium', 3.0, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (498, 'Axis', 'Cashback', 7.5, 'All');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (499, 'Standard Chartered', 'Millennia', 1.5, 'Entertainment');
INSERT INTO CreditCards (CardID, bank, cardType, cashbackRate, offerCategory) VALUES (500, 'IDFC', 'Gold', 1.0, 'Grocery');

